### ISSUE TITLE
Make identically named pages distinguishable throughout the UI

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#101]
If multiple pages located at different points in the site tree are named the same, it's currently not possible to distinguish between them when performing a search on the main Page tab or within page select boxes at various places in the UI. Something that is unique to each page needs to be added to help tell them apart.

Current data that is guaranteed to be unique between pages:
* Path
* Parent Page
* ID

We should avoid exposing IDs to endusers as much as possible, so it's a last resort.

**Comment by adamjohnson** [comment]
https://github.com/wvuweb/cleanslate/commit/d96a127fc844a61595bdb4cce631f1271c668489 closes this issue.

**Comment by nreckart** [comment]
This is also related to #180, which I believe is still a valid issue.
