### ISSUE TITLE
Site error logging system

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#102]
Providing a UI for viewing site related errors/info would be helpful for designers.

Useful Errors to Log:
* JavaScript syntax errors
* CSS syntax errors
* Radius tag errors

**Comment by adamjohnson** [comment]
We should add `config.yml` to this list.

**Comment by nreckart** [comment]
@adamjohnson Add what about config.yml?

**Comment by adamjohnson** [comment]
If `config.yml` can be invalid or cause a site to get hosed, then add that into the mix. Otherwise, ignore me.

**Comment by nreckart** [comment]
A site messages/errors feature was implemented in October with 943091f435b9ff3156468039cfad63b0f164430b.
