### ISSUE TITLE
List site owner on the Site Members page

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#105]
Pulled this from #104.

It's not clear in the UI that the site owner does indeed have access to the site. If someone is selected as a site owner, they should be automatically listed on the Site Members page.

With this, we know—unequivocally—that they have access and aren't a ghost admin user. The people listed on Site Members should be a complete list of people who have access to the site (except Super Admins, of course).

**Comment by adamjohnson** [comment]
**From #104:**

Yeah, top of the list sounds good. Should the site owner be in it's own table above members? Like:

| Site Owner: | Email: | Role: | Member For: |
|---|---|---|---|
| John Doe | john.doe@mail.wvu.edu | Administrator | 200 Years |

| Members: | Email: | Role: | Member For: |
|---|---|---|---|
| Jon Day | jon.day@mail.wvu.edu | Administrator | 100 Years |
| Jane Day | jane.day@mail.wvu.edu | Publisher | 50 Years |
| Jake Dawn | jake.dawn@mail.wvu.edu | writer | 25 Years |

**Comment by nreckart** [comment]
There will only ever be one site owner, so it would always be a table with a single row.

Could just stick it at the top of the existing members table, with a 'Site Owner' role.

| Members: | Email: | Role: | Member For: |
|---|---|---|---|
| John Doe | john.doe@mail.wvu.edu | Site Owner |  |
| Jon Day | jon.day@mail.wvu.edu | Administrator | 100 Years |
| Jane Day | jane.day@mail.wvu.edu | Publisher | 50 Years |
| Jake Dawn | jake.dawn@mail.wvu.edu | writer | 25 Years |

**Comment by zeroedin** [comment]
+1 for @nreckart 's version.

**Comment by nreckart** [comment]
Probably a separate issue, but the site owner should probably be displayed on the Site Overview page where all users can see it.

**Comment by zeroedin** [comment]
That sounds like a good idea.  Maybe with a message to those with a Role lesser than to contact this person for issues regarding site access and requests?

**Comment by nreckart** [comment]
Added the site owner to the existing site members table in 76a9b437bdf9d.
