### ISSUE TITLE
Tags are not removed when copying content from Microsoft Word

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#114]
This one is pretty self explanatory.  Without removing the tags from Word, the page ends up with a lot of extraneous, unnecessary code.

**Comment by zeroedin** [comment]
Related to #2

**Comment by adamjohnson** [comment]
Also see https://github.com/jejacks0n/mercury/issues/23.

**Comment by dmolsen** [comment]
I'm going to add a note that when we address #2 that we double-check the Word stuff. #2 is very much a near-term feature delivery.
