### ISSUE TITLE
Feature Request -- Cache clears on theme update or ability to manually clear cache

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#115]
Since pages are cached, any changes to code can't be seen for up to 15 minutes after they are made.  This slows down workflow and can be very frustrating at times, especially when trying to quickly correct code mistakes.  

This could be solved either by having a button to clear the cache manually, or having the cache cleared each time a theme is updated.

**Comment by adamjohnson** [comment]
Is this something [Hammer](https://github.com/wvuweb/hammer/) can't solve? You should be able to reproduce almost everything locally with Hammer and test your changes before you push to production.

**Comment by nreckart** [comment]
Related to #37.

**Comment by joshrcook** [comment]
Adam, I'm not sure Hammer is a great solution to this problem.  For example, recently I made a change to a template and pushed the changes, but no one could see those changes for at least 15 minutes or so, which prevented people that were working on that page from getting it done until the cache cleared.

**Comment by dmolsen** [comment]
@joshrcook -

Are you going to be around tomorrow afternoon (Friday)? Maybe I can meet with you in your cube and discuss this. I'm a little confused by the "prevented people that working working on the page." Maybe there's something else we're missing. Thanks.

**Comment by joshrcook** [comment]
Sure.  I'm free in the morning or anytime after about 2.

**Comment by dmolsen** [comment]
I'll stop by around 2.30. Thanks.

**Comment by adamjohnson** [comment]
@joshrcook -

Nathan deployed a number of changes (see #37) which should alleviate this issue. Can you confirm that there's no longer a 15 minute delay after hitting Sync Theme and you're not having any other caching issues?

**Comment by joshrcook** [comment]
This seems to be working fine.  Thanks, that's a great update!
