### ISSUE TITLE
Bug -- Links collapse next space after entering HTML editor

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#117]
In cleanslate, when you are editing an editable region that contains a link and you go into the HTML editor, the space right after all links collapses into the next word.  You can kind of see it in action in this gif.
![cleanslate-bug-2](https://cloud.githubusercontent.com/assets/2475205/5945461/93a2c408-a6fc-11e4-876b-d1ff74043f00.gif)

**Comment by adamjohnson** [comment]
Josh, could you edit your issue to follow the bug report format outlined in the [contribution guidelines](https://github.com/wvuweb/cleanslate-cms/blob/master/CONTRIBUTING.md)? That will help us better debug your bug report.

**Comment by nreckart** [comment]
This was being caused by a third party library that is used to cleanup the HTML for the editor. I updated the library and it no longer collapses space after links.

@joshrcook can you verify that this issue is resolved?

**Comment by joshrcook** [comment]
Yes, that works.  Thanks Nathan!
