### ISSUE TITLE
"More" class to menu items containing submenus...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#118]
Can we add another property for the site_menu snippet called "more_class" or something? If a menu has submenus and I want to have drop-down menus, I want to add a class called "more" to add an indicator there is a drop-down list.

**Comment by nreckart** [comment]
Added a `has_children_class` option to the `<r:site_menu>` and `<r:sub_menu>` tags.

Examples:

```
<r:site_menu max_depth="2" has_children_class="more" />
<r:sub_menu has_children_class="more" />
```

This has been deployed and is available for use.

**Comment by dmolsen** [comment]
Can this be closed? I would have assume @nreckart would close if it's been fixed but is this something where we wait for @adamglenn to confirm?

**Comment by nreckart** [comment]
Adam can close it if it meets his requirements. Don't believe he's had a chance to use it yet.

**Comment by dmolsen** [comment]
Got ya. Wasn't sure what your normal procedure was with the designers. Thanks.

**Comment by adamglenn** [comment]
Works perfectly.

**Comment by adamjohnson** [comment]
Docs updated:

http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-sub-menu

http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-site-menu
