### ISSUE TITLE
Radius tag(s) for generating image thumbnails

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#121]
@adamglenn requested Radius tags for dynamically generating scaled image thumbnails within a theme template, for use on the brand site.

**Comment by nreckart** [comment]
I created two new Radius tags for working with image assets.

```
<r:file:image_url>
<r:file:image_tag>
```

Both accept a `size` attribute in the format `widthxheight` (e.g. 250x150). Without a specified size, the unscaled image URL will be generated.

Example Usage:

```
<r:files labels="tag1,tag2" types="image" labels_match="any" by="title" order="asc">
  <ul class="thumbnails">
    <r:each>
      <li class="span4">
        <a href="<r:file:image_url />" class="thumbnail">
          <r:file:image_tag size="250x250" title="{file:alt_text}" />
        </a>
      </li>
    </r:each>
  </ul>
</r:files>
```

**Comment by adamjohnson** [comment]
Docs on CleanSlate CMS:

http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-image-tag

http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-file

http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-files-attr
