### ISSUE TITLE
Feature Request -- Voting on new features

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#122]
Just a suggestion here.  I know you had talked about having a place to vote on new features, so that others could give their input.  I'm not sure github is the best place for that, because there isn't any built-in way to vote on features besides the '+1', which is a little arcane.

One way I've seen work well is using Trello, because it does have a way to have a public facing board with a voting feature built in.  This could be even connected to github through Zapier, which would reduce the workload associated with updating two separate systems.  Here is a good example of a development team that has this up and running, although I don't think they integrate github:
https://trello.com/b/IZk2NDLt/ithemes-exchange-public-roadmap

Another solution, which might possibly be even better than that would be moving this repository to bitbucket.  Their issue tracker seems to be more robust than github's issue tracker, and it already includes the ability to vote for issues.

Anyway, just thought I'd at least put this up for discussion.

**Comment by dmolsen** [comment]
@joshrcook -

We will do a better job of communicating the "+1" policy. I'm not sure it's "arcane" as just making sure people are aware they can do it if they like.

Thank you for the suggestions but we will continue to stick to GitHub. It's something that works well for our internal team, allows us to handle a public/private mix for the project, integrates nicely with our deploy process and provides a mix a features we like. I don't see us needing to either add a new service or ditch our current one in favor of another service simply to get an "upvote" system. Hopefully I can keep track of +1s on issues here and prioritize them appropriately.
