### ISSUE TITLE
Add Slack Notification to Cap Deploy

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#125]
A slack notification for cap deploy would give me a good idea of how much was pushed in a week when I tally release notes. Looks like [it's pretty easy to set-up](https://github.com/j-mcnally/capistrano-slack). There are probably other libraries too. The notice could go to the #cleanslate channel.

Since this is noise that affects most everyone on the team I'd like to get 2 +1s to this idea before having Nathan implement. You have until COB Tue. Feb. 3.

**Comment by zeroedin** [comment]
+1

**Comment by nreckart** [comment]
I rarely do a full deploy do to the time it takes to rebuild assets. A full
deploy is only done if there have been JS or CSS changes, or for big
changes involving a large part of the code base. The majority of 'deploys'
are manual file pushes and app restarts. A separate cap task would probably
be best if you're looking for notifications every time new code makes it to
a prob box.

**Comment by zeroedin** [comment]
Would it be worth long term looking into something like this: http://sourcey.com/precompiling-assets-for-large-rails-deployments-with-capistrano/

**Comment by nreckart** [comment]
Maybe, but if I'm not mistaken, Rails 4 improves the asset compilation
noticeably. I'd hope to be able to deploy the Rails 4 branch in the near
future.

**Comment by dmolsen** [comment]
@nreckart -

A separate cap task would be great. Hopefully we can get another +1 from designers or Jay.

**Comment by adamjohnson** [comment]
Nathan has been pretty good about letting us know when he deploys in the past. That said, maybe a cap task would help automate this process a bit more. This is a addition/change to his workflow, so I'd say it's up to him. 

I'd imagine a `cap deploy notify` task would be easier than manually notifying us, but YMMV.

**Comment by jja006** [comment]
+1 I'm ok with the added noise as I think this will be a useful reference.

**Comment by dmolsen** [comment]
Please make it so, @nreckart. 

![make it so](http://images.simplysyndicated.com/wp-content/uploads/2014/07/make-it-so-captain.jpg)

**Comment by nreckart** [comment]
And what should this notification say?

**Comment by dmolsen** [comment]
:rocket: clean slate deployed to production. last commit: 09q87ow709234520

if the commit info is available that is. no worries if it isn't.

**Comment by nreckart** [comment]
@dmolsen, the gem you linked to, https://github.com/j-mcnally/capistrano-slack, doesn't appear to be actively maintained and it looks like it's using old Slack connection URLs. The web hook URLs Slack gives now don't match. There's a newer, actively maintained gem, https://github.com/supremegolf/slackistrano, but it requires Capistrano 3 and Ruby 2, neither of which we have right now. Capistrano 3 is already on the books in #95 and should happened after Rails 4 is deployed, #128. 

I'm looking at other options, but the integration is pretty simple so I may just roll my own quick and dirty.

**Comment by nreckart** [comment]
Created the cap tasks described below. We can roll with these for a while and adjust as needed.

### slack:deploying

This is fired when a full deploy is started. Not really sure how useful this one really is. Probably more noise than we need.

Example: 
CleanSlate (e14d602) is being deployed to production by Nathan Reckart at 04:44:31 PM.

### slack:deployed

This is fired after a deploy has finished. It includes how long, in seconds, it took to complete the deployment. 

Example: 
CleanSlate (e14d602) was deployed to production by Nathan Reckart at 04:47:52 PM. (201 seconds)

### slack:updated

  This will probably be the most often used. It should be manually called after incremental deployments.

Example:
CleanSlate updated on production by Nathan Reckart at 04:29:00 PM.

### slack:notify

This one can be used to send custom messages to stash, using the STASH_MSG environment variable.

Example:
`$> cap stash:notify STASH_MSG='Hello World'`
