### ISSUE TITLE
Steps for the Rails 4 Upgrade (e.g. get Clean Slate Staging working)

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#128]
The optimal path for this is:
- [ ] have Systems rebuild Clean Slate staging to match Clean Slate production
- [ ] have Systems build necessary gems (will get the list once we're at this step)
- [ ] merge the Rails 4 work into mainline branch
- [ ] deploy

This is becoming a blocker.

**Comment by adamjohnson** [comment]
Definite +1. Rails 4 has been chilling in the `wip/rails-4` branch for almost a year now—any by "almost a year", I mean we're five days shy of 1 complete year.

**Comment by jja006** [comment]
Nathan, did you want to log anything here and close this? Since we moved onto AWS and you were able to move to and past rails 4 some time ago. Thanks!
