### ISSUE TITLE
Page paths not working as expected

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#129]
## Steps to reproduce the issue
1. Log in to CleanSlate in the it.wvu.edu site.
2. Find the Microsoft Office Proplus Page.
3. Go to page properties / page paths.
4. Add `/services/office365/studentadvantage` and save
5. Go to `it.wvu.edu/services/office365/studentadvantage` in a new tab
## Results

It throws a 404
## Expected results

It should redirect to the Microsoft Office Proplus page
### Environment
1. Mac OS X
2. Google Chrome Version 40.0.2214.94 (64-bit)

![screen shot 2015-02-03 at 4 11 11 pm](https://cloud.githubusercontent.com/assets/2475205/6029550/51802a62-abbf-11e4-9d18-1fbaf078bc56.png)

**Comment by nreckart** [comment]
The "Microsoft Student Advantage" page already lives at '/services/office365/studentadvantage'. You'll need to choose another path for the "Microsoft Office Proplus" page.

The real issue here is that the Page Paths UI should notify and not allow duplicate paths to be created. I'll create a separate issue for that.

**Comment by nreckart** [comment]
I should also note that the "Microsoft Student Advantage" has not been published, which is why the 404 is getting thrown.

**Comment by joshrcook** [comment]
What if the content editor wants to check that the redirect works properly before deleting the page?  In this instance, that was the case.

**Comment by dmolsen** [comment]
@joshrcook -

Can't you just bin the page to a different path? Then test the redirect and delete if it works. If the redirect doesn't work then just change the path back. It's not like it's an either/or.

**Comment by dmolsen** [comment]
@joshrcook -

I'm closing this since there hasn't been a response. #130 should address the core issue that you brought up.
