### ISSUE TITLE
Link inserter not handling 'tel' protocol properly

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#132]
When I insert a 'tel' link into an editable region like this one: `tel:3042932316`, Cleanslate inserts `http://` before the tel link, which causes that link to break.
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Go to a page and select some text
3. Insert the following link as a URL: `tel:3042932316`
## Results

The link looks like this:  `http://tel:13042932316`
## Expected results

It should look like this: `tel:13042932316`
### Environment

![screen shot 2015-02-04 at 3 10 34 pm](https://cloud.githubusercontent.com/assets/2475205/6048669/0217999e-ac80-11e4-8778-2e8b229f68a7.png)

**Comment by nreckart** [comment]
@joshrcook try it now.

**Comment by adamjohnson** [comment]
I can confirm this works when you write `tel:5551231234` or `tel:555-123-1234`. :+1:

**Comment by zeroedin** [comment]
Just a development note.  

At this time do not expect tel: to work with phone number extensions across devices.  Apparently there are issues surrounding "pause" characters being different across devices.  

ie:

```
tel:1234567890pp123
```

would work on android but not on iOS

```
tel:1234567890,,123
```

would work on iOS but not android

Reference: http://stackoverflow.com/questions/3765777/inserting-a-pause-into-a-tel-link

It appears by specification the devices should ignore the extension so they do not cause a problem, but the UX for user may not be what was expected.

Early specification
RFC 2806: https://tools.ietf.org/html/rfc2806#section-2.5.6

Newer specification that removes that pause completely.
RFC 3966: https://tools.ietf.org/html/rfc3966#section-12

**Comment by zeroedin** [comment]
Ignore the reopen, misclicked.
