### ISSUE TITLE
VM for Hammer

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#134]
Not sure how possible this is but it'd be great if we could have a self-contained environment that's need to run Hammer. That way folks won't have to install things. I think this will take a bit of work to hook local theme files to the VM. Way outside my experience. Long-term solution but wanted to get something on the issues list.

**Comment by adamjohnson** [comment]
This issue should probably go somewhere in Hammer's repo instead/as well:

https://github.com/wvuweb/hammer

**Comment by dmolsen** [comment]
This issue is here for two reasons:
1. this is the only public issue tracker for all of the Clean Slate tools
2. i'm only going to check this repo to make sure we're on track with things

I'll ping this on the Hammer repo too though.

**Comment by zeroedin** [comment]
A VM is now available for Hammer, please see: [Hammer-VM](https://github.com/wvuweb/hammer-vm)

**Comment by dmolsen** [comment]
Kudos, @zeroedin .
