### ISSUE TITLE
Clean Slate Snippet Error for SiteImprove Policy

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#136]
For Slate we have "snippet error" as a consistent string that pops up if a snippet goes bad. Can we have something similar for Clean Slate so that we can add a SiteImprove policy that can alert site owners to snippets failing? I think a single base would be best but we can add multiple policies if that's better/easier.

**Comment by adamjohnson** [comment]
Policy is active in SiteImprove. This is done.

**Comment by nreckart** [comment]
Not done. There is no standard error string for snippet related errors for SiteImprove to key off of.

**Comment by dmolsen** [comment]
Sorry, thought I had taken care of that in SiteImprove. My fault.

**Comment by nreckart** [comment]
You may have, but CleanSlate doesn't output a standard message or string, which I believe is why you originally created the issue. All errors for all existing snippets and any future snippets will need to include whatever you set (have set) SiteImprove to key on.

**Comment by dmolsen** [comment]
Added a new policy in SiteImprove based on feedback from @nreckart . Will watch to make sure it "fires" but we should be good to go.

**Comment by nreckart** [comment]
Turns out snippet errors were already being wrapped in a `<div class="cs-snippet-error">`, which is what Dave set SiteImprove to key off of.
