### ISSUE TITLE
Cleanslate now requires the URL for @font-face to start with an extra " ../ "

### ISSUE THREAD

**Issue by architarious** [wvuweb/cleanslate-cms#139]
Not sure if this is a temporary issue or not. This doesn't seem to affect URL's in background images.

To better see what I'm talking about check out: http://diversity.wvu.edu

**Comment by nreckart** [comment]
This is happening because the icon font images are being stored in the /public directory of the theme. CleanSlate automatically replaces image URLs in CSS with a versioned URL, but only for '../images/blah' and '/images/blah' URLs. 

@architarious, is there a reason the images can't be put in the /images theme directory?

Using the ../public URLs means that the images will be cached for a full year and unless you manually edit the URLs in the CSS.

See #37 for more info on the caching.

**Comment by architarious** [comment]
Was talking about loading fonts instead of images. Only mentioned images because it affected SRC: URL('../your/url/here') in @font-face; not background-image: URL('../your/url/here').

..however my @font-face does have an SVG fallback, is that what you meant?

I'm not sure what happened, but it seems to be fixed now on the diversity site: http://diversity.wvu.edu/ 

It's still messed up on my testing site though if your still interested (cause i have to use only one '../' locally and haven't haven't switched anything to production yet): http://cpasstoolkit.sandbox.wvu.edu/

**Comment by adamjohnson** [comment]
Yeah I fixed the Diversity site. Working while on vacation, :balloon: :zap: . See [the `diversity` theme's commit log](https://stash.development.wvu.edu/projects/CST/repos/diversity/commits) to see how to fix it / what I did.

@dmolsen Be sure to explain this well in your blog post. Most folks are using `public` for icon fonts, so it's usually something like `../public/fonts/.....` that causes the issue.

Ideally we should be using SVG with PNG fallbacks for icons these days, but some older sites still use `.woff`, `.ttf` etc font files. This is where the public directory comes in.

**Comment by nreckart** [comment]
CleanSlate could be modified to rewrite 'public' URLs in CSS like it does 'image' URLs. I was trying to limit the amount of automagic being performed on CSS, but didn't realize public was being used.

@adamjohnson, is this worth doing?

**Comment by adamjohnson** [comment]
Yup, I think so.

Most folks are using public for icon fonts. This will slowly be replaced by SVG's with PNG fallbacks (images placed in the `images` folder). But, in the meantime, there are several live sites that use the `public` directory and reference files in `public` in their CSS.

**Comment by nreckart** [comment]
This should be fixed. @adamjohnson @architarious can either of you verify with a site using public for font icons?

**Comment by adamjohnson** [comment]
@architarious You should be able to sync cpasstoolkit.sandbox.wvu.edu and see if it worked or not. Hitting "Sync Theme" will bust the cache so we can properly test this.

**Comment by architarious** [comment]
It works: http://cpasstoolkit.sandbox.wvu.edu/ 

I'll let you all close the issue in case there's more stuff to post in this thread for records/reference reasons.
