### ISSUE TITLE
Feature Request -- Disable ability to incorrectly add an internal link

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#140]
When Lisa and I first started using CleanSlate, before we knew any better, we were adding internal links to pages using the "Url" field in the link UI.  We have since learned that you should use the "page" ui to link to a specific internal page, and only use the url field with an external link.  However, from time to time, someone who doesn't know the correct way or possibly forgets will insert a link (or in some cases lots of links) the wrong way, resulting in rework either by us or them.  

Would it be possible to basically prohibit internal links from the URL field?  I'm not sure if there are use cases where we would need to have an internal link that would use the URL field, but I can't think of any right off the top of my head.  This would probably parse the URL to either prohibit anything that starts with a '/', or anything that starts with the page url like "http://it.wvu.edu", "https://it.wvu.edu", or "it.wvu.edu/".  I don't think you would have to check against too many matches to rule out the majority of these internal links.

I think it would really help if the system enforced this best practice.  I try to provide training to people, but that doesn't stop all mistakes.  Thoughts?

**Comment by dmolsen** [comment]
@joshrcook -

We're looking into this one.

**Comment by adamjohnson** [comment]
![link-modal](https://cloud.githubusercontent.com/assets/575865/6310762/ff8951a4-b927-11e4-8860-a3f137e76600.png)

Some copy changes, should help. Site page is now checked by default.

**Comment by dmolsen** [comment]
Digging this solution, @adamjohnson. Like that it doesn't resort to a brute force programmatic solution in case it turns out we need to use that at some point. We'll see what kind of feedback we get to the changes.

This will most likely get rolled out next week, @joshrcook. Thanks for the suggestion.
