### ISSUE TITLE
Parse Error for RSS Feed on Info Sec Page

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#141]
The [info sec home page](http://it.wvu.edu/security) has the following error for an [embedded RSS feed](http://securelist.com/feed/):

```
This is not well formed XML Missing end tag for 'img' (got "div") Line: 127 Position: 8535 Last 80 unconsumed characters: 
```

I've hit it a few times in case you need a timestamp to review it should be around 3.45p on Friday Feb 20. I'm not seeing anything in NR but haven't logged into Gmail to review that list of errors. I have a copy of the XML feed in case this issue clears up over the weekend. FWIW, the W3C validator passes the feed but Chrome doesn't do any of the fancy highlighting.

**Comment by nreckart** [comment]
@dmolsen, I'm not seeing any error in Firefox or Chrome for the URL you provided. Where did you see the error?

**Comment by dmolsen** [comment]
@nreckart -

I'm thinking it was a bug in the feed at that exact moment. I'll email you a copy of the file if you want to run a test against it.

**Comment by dmolsen** [comment]
@nreckart -

Do you want to leave this issue open or should we close it?
