### ISSUE TITLE
Page Paths With Trailing Slash Don't Work

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#142]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Add a Page Path URL but add a trailing slash (stupid people like me don't follow examples)
3. Save
4. Try to hit the page path you added
## Results

You get a 404.
## Expected results

Should redirect to the canonical URL
### Environment
1. Mac. Safari.

/cc @joshrcook

**Comment by nreckart** [comment]
Can probably be handled along with #129.
