### ISSUE TITLE
Documentation of tags

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#143]
Hey guys, 

In order for theme developers to use CleanSlate to its fullest potential, it needs to be better documented.  I have tried to handle the documentation of the most commonly used tags, but there is still a lot to be done.  I know that only a fraction of them are fully documented, and even what is there can be added to.

I am willing to help as much as my schedule will allow, but I feel that this needs to be a concerted effort in cooperation with everyone there in UR Digital.  I would be willing to take a few each month and basically interview Nathan to find out what the tag can do, then write it up as I understand it.

According to Nathan, as of September 5th of last year, these were all available CleanSlate tags.  There may be more to add since then or additional features of tags that have changed since then:
r:image_url
r:include_javascript
r:include_stylesheet
r:breadcrumbs
r:comment
r:current_url
r:date_format
r:escape_xml
r:replace
r:select_html
r:set_var
r:site_name
r:var
r:ancestor_menu
r:site_menu
r:sub_menu
r:ancestors
r:ancestors:count
r:ancestors:each
r:children
r:children:count
r:children:each
r:current_page
r:descendants
r:descendants:count
r:descendants:each
r:get_ancestor
r:get_page
r:if_ancestor
r:if_childless
r:if_children
r:if_current_page
r:if_has_siblings
r:if_only_child
r:if_page_depth_eq
r:if_page_depth_gt
r:if_parent
r:next_sibling
r:page
r:page:alternate_name
r:page:attr
r:page:content
r:page:depth
r:page:first_non_blank_attr
r:page:id
r:page:meta_description
r:page:name
r:page:path
r:page:slug
r:page:template
r:page:template:name
r:page:title
r:page:url
r:page_name
r:parent
r:previous_sibling
r:root
r:siblings
r:siblings:count
r:siblings:each
r:unless_ancestor
r:unless_current_page
r:unless_parent
r:content_for
r:edit_mode_only
r:editable_region
r:if_content_for
r:partial
r:yield
r:yield:content
r:article
r:article:author_first_name
r:article:author_full_name
r:article:author_last_name
r:article:content
r:article:id
r:article:name
r:article:path
r:article:published_at
r:article:tags
r:article:title
r:articles
r:articles:count
r:articles:each
r:articles:if_articles
r:articles:if_no_articles
r:articles:pagination
r:articles:pagination:if_first_page
r:articles:pagination:if_last_page
r:articles:pagination:next_url
r:articles:pagination:previous_url
r:blog
r:file
r:file:alt_text
r:file:description
r:file:download_url
r:file:filename
r:file:id
r:file:name
r:file:title
r:files
r:files:count
r:files:each

**Comment by dmolsen** [comment]
@joshrcook -

We're going to talk about this internally tomorrow (unless we have more fires). I have an idea for how to approach this in a sustainable way but I want to see if it works with the rest of the team first. Thanks for suggesting this.

**Comment by dmolsen** [comment]
@joshrcook -

We're going to handle this internally. Thanks for offering to help. Nathan will work through and document the tags in the code. Then we can generate documentation from that that we can put in Clean Slate CMS. This way the person who is in the best position to describe the tags can handle it. I've marked this as a Q2 deliverable because we're quickly coming to the end of Q1.

**Comment by architarious** [comment]
What's the status on this?

The tag index on the CleanslateCMS site hasn't been updated in over a year: http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index

**Comment by adamjohnson** [comment]
@architarious Sorry to not have followed up on this sooner. We were out of the office at a conference when you commented. The date for the [tag index page](http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index) means that index page hasn't been updated in over a year; however, the child pages of that page have been updated much more recently (like [these](http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-blog-attr) [two](http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-page-if-has-content-for) for example).

I know Nathan was thinking about using rDoc or something for this; however, I think he's changed his mind on this. I'll let him update you there.

**Comment by adamjohnson** [comment]
Documentation is an ongoing need. I'm going to close this issue in favor of opening issues related to documenting specific tags.
