### ISSUE TITLE
Give a line number in CSS error messages

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#144]
If the CSS compressor / minifier errors out because of a syntax error, it doesn't give a line number for the original file so you can tell where the error originated from.  This would probably be helpful.

This is related to an issue I had recently with this stylesheet not loading due to an error:
http://rba.sandbox.wvu.edu/stylesheets/1424900881/styles.css

**Comment by dmolsen** [comment]
@joshrcook -

This feature is driven by Rails' asset pipeline. I'm not seeing a config option that would show a line number on a syntax error. Depending on what you use to build your CSS (editor or task runner) you may want to add a CSS linter to the mix to catch these problems locally. We'll keep this open as a low priority so we remember to check on the future updates to the asset pipeline for this feature.

**Comment by joshrcook** [comment]
@dmolsen - 

Yeah, that would work.  I just didn't know if that feature was built in.  Thanks for checking into this.

**Comment by adamjohnson** [comment]
https://github.com/wvuweb/cleanslate-cms/issues/102 closes this issue.
