### ISSUE TITLE
Ability to pass variables to partial

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#145]
Background for this request:
Right now, as it stands, partials are very static.  This is made especially obvious by Adam Glenn's new "Magic Pattern Library".  Take for example the first pattern on this page:
http://patterns.sandbox.wvu.edu/patterns

The reason you can't change the name of the college in this particular case is because all information inside a partial, that I know of, is completely static.  If it were possible to pass a variable to a partial all you would need to do to use that particular partial is this:

`<r:partial name="patterns/wvu-masthead" theme="adam-gs-magic-pattern-library" college_title="College Title" />`

I don't think this is currently possible, and I know the end result of passing variables to a partial wouldn't end up looking like that, but you get the idea.

**Comment by nreckart** [comment]
Partials already inherit the context into which they are included. So any variables set before the partial is included are available to the partial. Your example could be achieved by setting "college_title" prior to including the partial.

```
<r:set_var name="college_title" value="College Title" />
<r:partial name="patterns/wvu-masthead" theme="adam-gs-magic-pattern-library" />
```

I don't know much about the pattern stuff Adam is working on, so I can't comment about it specifically, but partials in general do not have to be 'very static'. They can basically do anything a regular template can do. How you choose to design and use them is up to you. I'm sure Adam can comment more on the design goals and intended use of his patterns.

**Comment by joshrcook** [comment]
That's great!  I thought there might be a way already but just wasn't sure.  The whole variable thing will be great to have documented when you guys get around to that so I don't need to come to you guys every time.

@nreckart - 

Is that the right way to include the partial, by the way?  Using the theme slug from stash?

**Comment by adamglenn** [comment]
The college name in those partials is not static. It is an editable region. Here is what that tag pulls in: 

``` html
<!-- WVU Masthead - wvu-pattern-library/views/patterns/_wvu-masthead.html -->

<div class="wvu-masthead">
  <div class="wvu-masthead__container">
    <r:partial name="patterns/wvu-masthead__logo" />

    <!-- If you are a department and want to link to your college or school, include the following line here: 
      <a href="" class="wvu-masthead__college-link wvu-gold background">Eberly College of Arts and Sciences</a> 
    -->

    <r:partial name="patterns/wvu-masthead__search-bar" />
  </div> <!-- /.wvu-masthead-container -->
</div> <!-- /.wvu-masthead --> 
```

Which pulls in other patterns e.g. the wvu-masthead__logo pattern:

``` html
<a class="wvu-masthead__logo" href="/"><span class="wvu-masthead__university-name">West Virginia University</span> <span class="wvu-masthead__title"><r:editable_region name="wvu-masthead__title" scope="site" /></span></a>
```

Which contains the editable region. Maybe you are confused by the comment in that partial. I have to get rid of that. There is a separate pattern to include the college name if you are a department, shown below:

``` html
<div class="wvu-masthead">
  <div class="wvu-masthead__container">
    <r:partial name="patterns/wvu-masthead__logo" />

    <a href="" class="wvu-masthead__college-link wvu-gold background"><r:editable_region name="wvu-masthead__college-link" scope="site" /></a> 

    <r:partial name="patterns/wvu-masthead__search-bar" />
  </div> <!-- /.wvu-masthead-container -->
</div> <!-- /.wvu-masthead --> 
```

Here is how you reference it:

``` html
<r:partial name="patterns/wvu-masthead--department" />
```

**Comment by nreckart** [comment]
@joshrcook No, you'd need the theme name in CleanSlate. Updated the example. The theme slug stuff you're referring to would be related to #124.

**Comment by joshrcook** [comment]
Sounds like this is solved.  Thank you.

**Comment by joshrcook** [comment]
@nreckart -

Sorry to kind of add on to this, but could you remind me how you would access that variable within the partial?  And could you also include something that shows an if then statement, if that capability is available.  Basically, if this variable equals true, show this code?  I could really use this for another project I'm working on now.

**Comment by nreckart** [comment]
To output a variable you would do: `<r:var name="college_title" />`

To use a variable within the attribute of another radius tag you would do something like the following:

```
<r:descendants:each order="{$order}"  by="name" labels="{$tags}">
  other stuff here
</r:descendants:each>
```

In the example above, order and tags are variables. They could be set in various ways (url, set_var, standard page attributes, custom page attributes).

Conditional logic cannot be used with variables at this time, but that ability could be added in the future.

**Comment by nreckart** [comment]
@joshrcook 

Some basic conditional logic support has recently been added. You can read more about it at http://cleanslatecms.wvu.edu/how-to/theme-development/conditional-logic-loops. The initial tag documentation is also available at http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-if-and-r-if-not.

**Comment by architarious** [comment]
Used the above to devise some logic that pulls content from different sets of faculty profiles depending on if their programs abbreviation happens to be set as the current page's alternate page-name: https://stash.development.wvu.edu/projects/CST/repos/cpass-discover/browse/views/components/academic/_m-academic_facultyList.html

I might rework the alternate page-name aspect later, but I figured I would go ahead and share in case someone else also needs to do this sorta thing.
