### ISSUE TITLE
Handle page template assignments that no longer exist

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#146]
If the theme for a site is changed, there is no guarantee that the new theme contains the same templates as the old theme. So any pages that already exist when the theme is changed could potentially be busted because they are assigned a template that no longer exists in the new theme. This issue would also present itself if a template is removed from a theme for some reason, but has already been assigned to existing pages.

I'm seeing this occur more often as time goes on. Currently the application throws a 500 error when a page without a valid template assignment is visited. Unless a site designer/owner/user actually visits an affected page, they wouldn't know the error is occurring. If I see it occurring repeatedly for the same page, I'll notify the appropriate party. Eventually, errors such as this could be logged as described in #102, which would make the visible to relevant site users, but we should probably come up with a way to handle this particular issue in the near term.

What is the best way to handle this situation? I'll throw out some options to get the discussion started.
1. A nightly job could be run for every sight and a report could be emailed to ??
2. Every time a theme is synced, a report could be emailed to ??
3. A message similar to the "This site doesn't have a default page assigned" could be displayed. This would basically have to run every time the admin UI is used for the site, although it would be cached for a brief period.

Feel free to offer up other suggestions.

**Comment by joshrcook** [comment]
@nreckart If there is a default page template, could the pages that are orphaned be assigned that template by default?  And then maybe there could be a report on top of that?  That would at least stop the 500 error from being thrown.

**Comment by nreckart** [comment]
This was handled along with #102.
