### ISSUE TITLE
Breadcrumb HTML output

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#148]
Currently the output for the `<r:breadcrumbs />` tag looks something like this:

```
<ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">Page Parent 1</a></li>
    <li><a href="#">Menu Item 2</a></li>
    <li>Current Page</li>
</ul>
```

I would like to suggest that a `<span>` tag be added around the 'Current Page' item.  This came up recently because I was putting a slash character between the `<a>` tag and the `<li>`, but there isn't a way to select just the text of the last `<li>` without selecting the `<li>` itself.  This shouldn't break current CSS, and it would allow an extra selector for CSS.

**Comment by adamjohnson** [comment]
Josh,

Are you trying to do this?

http://codepen.io/adamjohnson/pen/Jomjzg

Would you mind posting a link to either where you're using this or perhaps a pen/jsfiddle of what you're going for?

This may end up being an attribute that you can add to `r:breadcrumbs` to add a `class` or `id` to the `<li>` (if it's not already there).

**Comment by joshrcook** [comment]
Yeah, something like that.  I actually figured out a way around it with CSS after I looked at it again.  I still think it would be a good idea, but it's not imperative or anything.

**Comment by adamjohnson** [comment]
I'm going to close this for now until someone requests the ability to add a `class` or `id` to the `<li>`. Bigger fish to fry and all...

**Comment by joshrcook** [comment]
Yup, that works.
