### ISSUE TITLE
Can't scroll in Mercury Editor

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#151]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Open a page to edit that has lots of content (aka creates a vertical scrollbar).
## Results

The browser doesn't scroll vertically with a trackpad or mousewheel.
## Expected results

Users should be able to scroll down the page by using their trackpad or mousewheel. 
### Environment
1. OSX Mavericks+ & Windows 7+.
2. Chrome 41, Safari 8.
3. Mercury 0.9.0.
### Notes:

You can work around this by 
- Opening the HTML modal and then closing it. After the HTML modal gets closed, the page is available to scroll. OR...
- Resizing your window.

This "scroll-lock" behavior is fixed in Chrome 42 (currently Beta/Canary). You can [download Chrome Beta](https://www.chromium.org/getting-involved/dev-channel) if you want this fixed right now.

![support-deetz-chrome](https://cloud.githubusercontent.com/assets/575865/6852363/9c8a90a6-d3ba-11e4-98d7-5011879b36ae.png)

This issue is related to jejacks0n/mercury#270. The same behavior happens on [Mercury's Demo](https://jejacks0n.github.io/mercury/) when the page first loads.

**Comment by nreckart** [comment]
Mercury does some funky sizing/positioning stuff to get the toolbar, status bar, and site iframe to all play nice, which is pretty confusing. We also have to tweak it a little to handle our top menu bar correctly, which makes it even more confusing. All of the work arounds Adam mentions work by triggering the resize event for Mercury, which recalculates and repositions everything. Triggering the resize event after the iframe has finished loading seems to fix the issue.

**Comment by adamjohnson** [comment]
Nathan's fixes cause a double vertical scrollbar when you're editing content in Mercury. While not visually ideal, these changes do fix the main issue at hand. 

When Chrome 42 comes out, we can look into rolling back to this change since Chrome 42 fixes this issue natively.

**Comment by nreckart** [comment]
@adamjohnson Safari would still be busted.
