### ISSUE TITLE
Move page beneath another page with children "As Child" 

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#152]
## Steps to reproduce the issue

Here's a video outlining the issue: http://screencast-o-matic.com/watch/cof22seS1O
1. Log in to CleanSlate.
2. Go to a site > Pages.
3. Make sure your site has a page with nested pages under it.
4. Move a page at the root "As child" of a page with nested pages.
## Results

The "As Child" option doesn't show up on the page with nested pages.
## Expected results

The "As Child" option should show up. Once clicked, the page being moved can then go to the bottom of the nested list (as per usual).
### Environment
1. Operating System: All
2. Browser & Browser Version: All

Issue reported by @osteffich. She thought clients might be confused by not having this option.

**Comment by dustinmazon** [comment]
I agree with Octavia, I think the issue isn't only for clients but even I was a little confused when I tried to "add as child page" to the parent and the option wasn't there. I figured out you can just add above or below a sibling but initially I was kind of confused as to why the option to add as child disappeared. First time users could definitely have problems with this.

**Comment by bokster** [comment]
+1. I just encountered this.

**Comment by jasonmarkle** [comment]
+1 I have run in to this issue before as well.

**Comment by nreckart** [comment]
The 'As Child' option should always be displayed now.
