### ISSUE TITLE
Request: Custom content types

### ISSUE THREAD

**Issue by chrisyuska** [wvuweb/cleanslate-cms#153]
I've had several offices request features that require data storage and don't fit neatly into the blog article model.  A custom content model could satisfy each of these requests.  LocomotiveCMS describes this "Content Type" concept [here](http://locomotivecms.com/features#custom-content) and their model implementation can be found [here](https://github.com/locomotivecms/engine/blob/master/app/models/locomotive/content_type.rb)

Here are two recent examples of feature requests that I've received:
1. A page that contains a searchable list of all faculty and staff, along with their area(s) of research, department, website link, and bio.  Note that each faculty item in the collection may have multiple areas of research, and this must be searchable.
2. A page that contains a searchable list of job postings.  Each item in this collection would have a title, department, description, and contact link at the least.

As far as I'm aware, CleanSlate doesn't currently offer a solution to this need.  Creating a custom content type would meet current needs and provide enough flexibility to meet most future storage needs.

**Comment by adamjohnson** [comment]
Chris, have you played with pulling information from faculty profile pages? Check out [these profile pages](http://honors.wvu.edu/profiles) on the Honors College site and the [`profile_individual.html`](https://stash.development.wvu.edu/projects/CST/repos/honors-college/browse/views/profile_individual.html) and [`profile_index.html`](https://stash.development.wvu.edu/projects/CST/repos/honors-college/browse/views/profile_index.html) pages on Stash.

Basically, the content you see on the profile_index page is pulled from each profile on their respective page. A content editor can update the information on the individual page and it's updated everywhere. the `r:children:each` tag is doing the heavy lifting in the `profile_index.html` template. All of the content is searchable; although I have a feeling that you might be looking for something fancier. Something like [jQuery Isotope](http://isotope.metafizzy.co/) perhaps? I know Dave Davis was going to implement something like this for the Eberly College redesign before he started working for Libraries. I believe he posted a mock up in Conceptboard if you wanted to check it out. I used Isotope on [an old Slate site](http://memories.wvu.edu).

There's also [Custom Data](http://cleanslatecms.wvu.edu/how-to/theme-development/custom-data). And then there's also `r:edit_mode_only` which you could use for adding data to a page that isn't necessarily shown on a page but could be pulled into other pages. `r:edit_mode_only` is kind of a stopgap solution for page attributes until that functionality is explored further. 

If you're looking for an in-site search, that's related to #12. But you could take [these instructions](http://cleanslatecms.wvu.edu/how-to/theme-development/search) and point the search URL (`value="<r:site:domain />"` to the specific pages you want to search (list of faculty and staff & another one for your job postings). 

I know @dmolsen & @dustinmazon were thinking about this topic as well. They may be able to weigh in further.

**Comment by dmolsen** [comment]
I can't really weigh-in with much more. We need the search feature for an upcoming project. Based on what you've shared a template acts, I think, as our "content type." Basically the template is our form and the content areas are the attributes we can use elsewhere (including `r:edit_mode_only`). The prototypical example is the profile example @adamjohnson discussed.

**Comment by chrisyuska** [comment]
Thanks for the responses.  The solution with the individual profile pages combined with js is certainly sufficient for small lists, but it runs into practicality issues as the number of pages needed increases.  For the faculty list project I mentioned above (1), the list of faculty is 120 people right now.  This doesn't create a massive amount of overhead to load or filter with js, but creating 120 profile pages in CleanSlate is pretty tedious and currently impossible to automate.

Since there are valid solutions to the problem of custom data already in place, perhaps the issue is really that these problems rely on developers to be solved.  I could create something akin to what @adamjohnson suggested with the profiles, but then I need access to the Stash repo to update the theme, and finally I may have to create the 120 pages with custom data myself depending on how technical the normal site maintainer is.  A solution that allows the non-technical site maintainer to define the page type with custom data fields in CleanSlate, and then create the 120 pages themselves with at least a simple parent index page for the pages would be great.  Here's a sample userflow that I'm picturing:
1. Site maintainer clicks on the "+ Create Page" in CleanSlate.  An additional option for "Custom Data Index" is shown in the list of page types.
2. User selects the "Custom Data Index" link, and it opens a form similar to the new page form now, except that it includes fields for custom data attributes.
3. User fills out form with custom data attributes as needed, and clicks "Create" button.
4. User can then add child pages with the "+ Add Child" link that automatically have the custom attribute fields in their creation forms (or at least editable sections on the pages' editor view).

The "Custom Data Index" page can default to the backpage template and dump the children into a table for most offices' needs.  For prettier solutions, we can develop something custom for the site's theme, but giving non-technical maintainers the power to create basic solutions to meet their changing needs enables them to do a lot more without having to rely on us developers for everything.
