### ISSUE TITLE
Requirements for Gather Content Integration

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#158]
These are the requirements for integrating Clean Slate with [Gather Content](https://gathercontent.com/). I assume this is a rake task that any of us will be able to run when we need to sync content.
- [ ] will only support a one-way transaction (_from GC to CS_)
- [ ] will _not_ support file downloads. It'd be nice to get the content this way but I have no idea how we'd relate the code to snippets.
- [ ] can't hardcode the integration info (_e.g. GC API keys, GC project IDs, GC account names, CS root page_)
- [ ] must be able to update an existing page via storing the GC page ID as a custom attribute related to the page template that's being used
- [ ] the content region keys in the theme templates must match labels used in GC. The content region keys should be the lower-cased and underscore delimited version of the `label`. For example, the label might be "Major Name" and the content region key to match to the template would be "major_name."

They have some very simple [developer docs](https://help.gathercontent.com/developer-api/). I'm assuming these are the steps that would have to be completed for this to work:
- [ ] run the rake task with the options from above
- [ ] send a `POST` request using digest authentication to the `https://wvuurdigital.gathercontent.com/api/0.4/get_pages_by_project` endpoint. Pass `id` (for project ID) as a POST var. The GC API doesn't currently support oauth.
- [ ] if this only returns page IDs then loop and send another `POST` request using digest authentication to the `https://wvuurdigital.gathercontent.com/api/0.4/get_page` endpoint. Pass `id` (for page ID) as a POST var.
- [ ] read the `config` attribute of the returned JSON and base64 decode it to get the content
- [ ] based on the CS root page see if a CS page w/ has the GC page ID as a page attribute exists. If it does update CS content regions with the new info. If not create the new CS page plus related content regions. 

That should be it. Let me know if you have any questions.

**Comment by dmolsen** [comment]
@nreckart -

You can find your API key under your personal settings (top right nav. click the avatar).

**Comment by dmolsen** [comment]
@nreckart -

We should probably only update when content has a state or status of Approved.

**Comment by nreckart** [comment]
Should pages only be imported if they are Approved?

**Comment by dmolsen** [comment]
Yes.

**Comment by nreckart** [comment]
What user should be used when creating/updating pages in CleanSlate? This is who would show up as creating or updating the page in the audit/history logs.

**Comment by dmolsen** [comment]
Oof. Good question. Let's create a local Gather Content import user. That way we can easily track what a "bot" did versus any of us.

**Comment by nreckart** [comment]
How would a content region named 'Student Profile #1 Name' in GC get converted to a CleanSlate region key?

student_profile_1_name
student_profile_#1_name

Basically, how are non alpha numeric characters handled?

**Comment by dmolsen** [comment]
Let's go with a literal there. I can update it so it's 'Student Profile 1 Name'

**Comment by nreckart** [comment]
Should pages be ordered alphabetically? The sort field in GC is set to 9999 for everything.

**Comment by dmolsen** [comment]
I think import order is fine as an order. So if Zoroastrian Studies comes before Animal Husbandry in the import it's ok if the former is ordered above the latter. Can manually fix.

**Comment by nreckart** [comment]
Should pages be automatically published in CleanSlate on import/sync? What date should be used as the publish date? When the import/sync was done or the last updated date from GC?

**Comment by dmolsen** [comment]
Without a "select all pages" > "publish" (not asking for it) I guess yeah it should be published on import. Publish date should be the import date. That way it'll keep track of when Clean Slate was touched/updated.

**Comment by nreckart** [comment]
Can we close this?
