### ISSUE TITLE
Requirements for Simple Content Search of a Subset of Pages on a Site

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#159]
Simple content search can be broken down into two parts. The first is a JS-based solution that possibly uses [typeahead.js](https://twitter.github.io/typeahead.js/). The second would be a simple search that can be used in case the user has disabled JS.

For the `typeahead.js` solution we'd need to be able to do the following:
- [ ] ~~create an inline JSON object of selected attributes from pages based on a given root page. In this case we'd be targeting three properties (_keywords, title, and areas of emphasis_).~~

That's it.

For the non-JS solution... maybe this is a job for the Google Search Appliance. Or is this something that can be done with somewhat decent accuracy via the tools we already have? I don't need fuzzy matching. It'd be nice but it's not a requirement. So it'd work like this:
- [ ] submit keyword
- [ ] compare against selected attributes from pages based on a given root page
- [ ] return a list that can be styled via a custom template

I expect the non-JS solution to be more difficult.

**Comment by nreckart** [comment]
@dmolsen 

When you say "compare against selected attributes from pages based on a given root page", what attributes are you referring to? I'm assuming content areas for a page, which aren't really 'attributes'. What other attributes?

**Comment by dmolsen** [comment]
content areas or the `custom_data_attributes`. i'm just not sure how one would tag content from GC to go into one versus the other.

**Comment by nreckart** [comment]
I'm trying to make the content searching a little more flexible, but it would help to know some examples of how you intend to search for things. Some example search phrases/terms would be helpful. 

What kind of searching should the system support? How complex? Does it need to support AND, OR, NOT, quoted phrases? So basically a full blown search engine? Or can is simply treat each word in the search phrase as an AND or and OR?

You can find some of the possibilities at http://www.postgresql.org/docs/current/static/textsearch-intro.html. It gets pretty tricky in a hurry.

**Comment by dmolsen** [comment]
For now it's just major names or subjects so "biology," "engineering," or "art" are good terms. Something like "mechanical engineering" we can treat as an AND. Do you need to know editable regions to search or does it just do everything?

**Comment by nreckart** [comment]
So I built it with two modes. Simple and advanced. Simple basically takes a search phrase and joins all words with AND. Advanced mode assumes that the search phrase already includes the appropriate operators (&, |, !). You toggle the mode via an attribute for the Radius tag within the template. You can also specify a list of region keys to limit the search to, or search everything.

Below is a simple example, using the advanced mode. It will search the major_name and program_description fields for all pages under the current page. The `cquery` is passed in via a URL query param.

```
<ol>
  <r:descendants:each content="{$cquery}" content_keys="major_name,program_description" content_advanced="true" by="name">
    <li><a href="<r:page:url />"><r:page:name /></a></li>
  </r:descendants:each>
</ol>
```

**Comment by dmolsen** [comment]
@dustinmazon -

Just looping you into this convo so you get the code for using @nreckart's search feature. 

Based on Nathan's example in the previous comment you'd want to:
1. Create a form that had a method of `GET` and an action of `/academics/majors/`.
2. The input type text would have the name `cquery`
3. `/academics/majors/` would have a unique template that allowed it to double as base page for the section listing all majors and a results page for the search because all of the majors are descendants (see code above). I guess you can check to see if `cquery` has been defined before deciding if you show all the descendants or just those that need to show up because of the search.

**Comment by nreckart** [comment]
If cquery is not specified in the URL, all pages would be included in the loop by default.

**Comment by nreckart** [comment]
Can we close this?
