### ISSUE TITLE
Editor leaving behind empty headings

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#160]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Highlight an `<h3>` and change it to a heading 4 using the Cleanslate interface (tested at https://cleanslate.wvu.edu/sites/169/pages/6660/editor)
## Results

It changes the tag to an h4, but also leaves behind an empty h3
## Expected results

It's not supposed to leave an h3 behind
### Environment
1. Mac OS X
2. Chrome 42.0.2311.135

![screen shot 2015-05-12 at 9 53 30 am](https://cloud.githubusercontent.com/assets/2475205/7588716/d28b39ca-f88c-11e4-9aa4-448ce4dfc9d2.png)

**Comment by adamjohnson** [comment]
This is a `contentEditable` issue, not a CleanSlate issue. It happens on [the Mercury demo](https://jejacks0n.github.io/mercury/) as well. As I've said previously:

> Many of the things you have specified deal with the HTML5 ContentEditable attribute that Mercury (our editor) uses. The crappy markup that you’re seeing stems from lack of any standards around that attribute and different implementations by browser vendors. 
> 
> The guardian team is documenting these here:
> 
> https://github.com/guardian/scribe/blob/master/BROWSERINCONSISTENCIES.md
> 
> Long story short, these bugs are due to a lack of clear, defined standards from browsers & their implementors. We’re looking into workarounds for the moment, but the best thing to do to get these fixed would be to contribute on these open source projects (like Mercury and Scribe) and file/star bugs with browser vendors.

#2 is related to this and [this Medium article](https://medium.com/medium-eng/why-contenteditable-is-terrible-122d8a40e480) is worth reading.
