### ISSUE TITLE
Link to file doesn't work in editor mode

### ISSUE THREAD

**Issue by dustinmazon** [wvuweb/cleanslate-cms#162]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Upload a PDF file to your site.
3. Go to a page in editor mode.
4. Click in editable region and add a link to the PDF file.
5. Save editable region and test link.
6. Error: link has the domain https://cleanslate.wvu.edu/......
7. Publish editable region and test link.
8. Error: link has the domain https://cleanslate.wvu.edu/......
## Results

Basically there is a "Resource Not Found" error because the true path to the link starts with the site domain not https://cleanslate.wvu.edu/
### Error in Editor View

![screen shot 2015-05-27 at 5 30 25 pm](https://cloud.githubusercontent.com/assets/1126703/7848249/215ed32e-0498-11e5-951c-7d3bbbba89df.png)
### No Error in Live View

![screen shot 2015-05-27 at 5 46 25 pm](https://cloud.githubusercontent.com/assets/1126703/7848279/69368b10-0498-11e5-9b6f-8df9504e2d0a.png)
## Expected results

I think from a user standpoint they expect the links to work in the editor mode when saved or published so that they can test them out. When users click the link and it responds with "Resource Not Found" they think the file is broken or not there.
### Environment
1. OSX
2. Chrome Version 43.0.2357.81 (64-bit)

**Comment by dmolsen** [comment]
I ran into this a few times with the Admissions site. It'd be nice to get it cleaned up if possible. Added a delivery date on it.
