### ISSUE TITLE
Add async and defer attributes to r:include_javascript

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#163]
Currently there's no way to specify `defer` or `async` for an `<r:include_javascript />` tag. Async and defer can help perceived performance of your site by not preventing HTML render. Here's some ideas about how to include those in a CleanSlate template:

``` html
<r:include_javascript name="example" async />
<!-- or -->
<r:include_javascript name="example" async="true" />

<!-- generates -->
<script async src="/javascripts/123456/example.js"></script>
```

Same thing for `defer`. Just replace `async` above with `defer`. 

Resources:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
http://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html

**Comment by dmolsen** [comment]
Do prof techs normally include JS in places outside of the just above `</body>` regularly? I'm intrigued by this but it doesn't nothing if that's the normal way people approach JS.

**Comment by adamjohnson** [comment]
Most prof techs blindly follow whatever the docs tell them. Oftentimes the docs tell them to include JS in the `<head>` (like [FlexSlider](http://www.woothemes.com/flexslider/)). Alternatively, they will put it in the footer, see if it works, then, if it doesn't, they move it to the head as a means of debugging.

**Comment by dmolsen** [comment]
I think it's a good addition (added a date to this one) but I'm sure it might cause you guys headaches a little based on inexperienced users.

**Comment by nreckart** [comment]
`<r:include_javascript name="example" async="true" />`
and
`<r:include_javascript name="example" defer="true" />`

Are now supported. Both attributes are optional. You could even use them both together, but the world may explode.

The actual content generated for the async bit is `async="async"`, because that's how Rails handles it, apparently. Shouldn't matter in practice.

**Comment by zeroedin** [comment]
From the specification: http://dev.w3.org/html5/spec/single-page.html#attr-script-async

> The defer attribute may be specified even if the async attribute is specified, to cause legacy Web
> browsers that only support defer (and not async) to fall back to the defer behavior instead of the
> synchronous blocking behavior that is the default.

:+1:

**Comment by adamjohnson** [comment]
Updated the docs to include `async` and `defer`:

http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-include-javascript

Thanks everyone!
