### ISSUE TITLE
Don't output blank ID's on images and links

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#165]
## Steps to reproduce the issue
1. Log in to CleanSlate. Choose a site.
2. Edit a page. Add a link or image.
3. Publish.
## Results

If you add a link or an image to a page, it will output something like this:

``` html
<a href="https://cleanslate.wvu.edu/sites/14/pages/1087/editor" data-page-id="1087"
class="" id="">link</a>
```

Note the `id=""` bit.
## Expected results

CleanSlate should not output blank `id`'s. Blank `id`'s fail in the [W3C validator](https://validator.w3.org/check?verbose=1&uri=http://universitycollege.wvu.edu/). If a page has a bunch of images and links, these validation errors add up _quickly_. 

![duplicate-id s](https://cloud.githubusercontent.com/assets/575865/8134581/51a87fae-10fe-11e5-8203-ad8f828ce039.png)

Fixing `class=""` being output would also be awesome when fixing this issue; however, this isn't required.
### Environment

All.

**Comment by adamjohnson** [comment]
Looks like `id=""` also happens when inserting a video via Media > Video and Snippets that have class and ID options.

**Comment by nreckart** [comment]
Blank id and class attributes should be gone from this point forward when inserting links, images, and videos. Blank attributes created from previous content will remain.
