### ISSUE TITLE
HTML caching in Public directory

### ISSUE THREAD

**Issue by dustinmazon** [wvuweb/cleanslate-cms#167]
## Steps to reproduce the issue
1. Add an HTML file to the public directory. `wvumag.wvu.edu/public/emails/example-email.html`(I am wanting to use the public directory to store my HTML emails.)
2. Git Add, Commit, and Push
3. Sync wvu-magazine theme in Cleanslate 
4. Make edit to HTML file.
5. Git Add, Commit, and Push
6. Sync wvu-magazine theme in Cleanslate 
## Results

After an HTML file has been synced any edits to that file name are cached in Cleanslate. The only way to make edits to an existing HTML file located in the public directory is to change the file name. 
## Expected results

I would like edited HTML files from the `public` directory to sync with changes to the repo. Notice in the screenshot below I have had to change the file name by adding a -1.html to the end so that the changes can be seen. When I send this out for people to review it is nice to be able to use the same URL.

![screen shot 2015-06-22 at 1 51 30 pm](https://cloud.githubusercontent.com/assets/1126703/8288710/da3565aa-18e5-11e5-8a50-a86fe0c79200.png)

I know there might be a reason why the HTML is cached and if this issue can't be resolved I will have to come up with another approach quickly so that I am no longer dependent on Slate for HTML emails. Using the `public` directory seemed to be the best approach for handling HTML emails university-wide since Prof Techs have already have access to Cleanslate themes.

**Comment by zeroedin** [comment]
Again I know this is beating a dead horse, but the real solution for this is the ability for you to deploy on static.  So you do not have to rely on the CMS to store this content.   /cc @jja006

**Comment by adamjohnson** [comment]
@dustinmazon When you hit the email in your browser, can you add a timestamp to the URL to bust the cache? EG:

http://wvumag.wvu.edu/public/12345/emails/wvumag-2015August19.html
- @osteffich 

@zeroedin other designers need this too.

**Comment by nreckart** [comment]
The caching is working as intended. See #37 for details.

**Comment by dmolsen** [comment]
I'm with @nreckart that this should be the way we expect Clean Slate themes cache settings to work. If we need to set-up different repos elsewhere for HTML emails that's fine. We just need to lay out what the process is for development, review and production of the emails so we can build the right set-up. Outside of the two days after July 4th I'm around so if designer(s) want to sit down and hash it out lets get it done. Shoot me a cal invite.

**Comment by dmolsen** [comment]
for historical purposes @jja006 said...

Dave, we can probably use existing static host that is in place. the issue is opening that up for deployment - we could add Dustin or Adam probably (request to ITS to either add them to user-deploy group, or establish a separate group/access) but I don't think we want to do that for ALL of the prof-techs? (meaning, not doing it for prof. tech's outside our department, if that makes sense). Steve has a project setup in stash for the static host (static.wvu.edu) and there are multiple repos in that project, probably a good way to do it

**Comment by dmolsen** [comment]
To which i would respond... I think the solution is in web hooks but cache should also be fleshed out.
