### ISSUE TITLE
New blog post type: External Link

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#169]
Several people have requested to be able to create a blog post that links to external articles. Many times, these links go to WVUToday. For example, here's the B&E site's blog which has about 40% of their blog posts linking over to WVUToday:

http://www.be.wvu.edu/news_events/index.htm

So, here's how it could work:
1. Click "Add Child" on the blog index page
2. Modal pops up and says: ![blog-external-link](https://cloud.githubusercontent.com/assets/575865/8336602/b0e2287a-1a73-11e5-8163-49e95a807cd5.png)
3. After clicking "Blog Article: External Link," the standard "External Link" modal pops up with a few extra fields: Post description, post source ("WVUToday"), and maybe author (?).

What do people think about this? Are the new fields appropriate? Blog Article: External links can automatically be published just like their external link counterparts.

If this can be achieved in another way that wouldn't need new development, please let me know. Also, let me know if I can help in any way.

**Comment by zeroedin** [comment]
As an FYI, on WVUToday this feature, is nothing more than a standard article element with an additional "URL" field.  If the external URL was present everywhere the article was linked would go to this external URL.  

This was done so if the "external link" was ever changed or was removed from the 3rd party site the URL could be removed and separately stored content could be shown.  This content could have been created or copied into the standard article fields from the external page before publish.  

With that said I'm unaware that it was every used in this way so might not be important to do so.

**Comment by adamjohnson** [comment]
cc @ericalindsay

**Comment by adamjohnson** [comment]
@zeroedin brought up a valid point. Blog post authors may want more than just plain text for their External Link Blog Articles (for example, a [blog post thumbnail](http://code.tutsplus.com/)). 

Perhaps it is best to make the external link blog post a page/blog article. This would allow the author to customize the content accurately and would also satisfy content in the RSS feed.

Theoretically speaking, it might not be hard to implement. Almost an exact copy of the Blog Article modal. One extra field when you choose your blog post type ("Blog Article: External Link", see screenshot above), then only one extra field in the post properties modal (External URL). Then, when the page is published, all the links in the post (eg Post Headline & "View Post" button) go directly to the external article. 

Make sense?

**Comment by jasonmarkle** [comment]
@adamjohnson @zeroedin +1 to this idea. I just had a request yesterday to do this in our old system, which is super hacky and it's not the best in terms of practices, but it was to push one of the new Project Me pages about one of our engineers. I could foresee this being an issue at other colleges as the new brand continues to grow and evolve, especially if they have news sections where they rely on other sources of material from around the university that pertain to them.

Specifically, @adamjohnson is making a good suggestion with the formatting of how it should link as well.

**Comment by adamjohnson** [comment]
Closing this because a page template (like `blog_article_external.html`) handles this adequately.
