### ISSUE TITLE
Remove auto-styled images

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#173]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Click pages > edit any page with an editable region in a new tab.
3. Click inside the editable region and select 'media' in your UI.
4. Upload an image, or select an image and insert it in to the region - don't forget that sweet Alt tag!
5. Open the code terminal from the UI to view the code and see the automatic style tag
## Results

You'll notice that after the image src is called in, there will also be a few styles being called as well, some of which usually dont have any real implications (like font styles) but other such as height and width styles will break the images capability to be served on other screen sizes and cause it to stretch.
## Expected results

Expect it not to bork, but it borks!
### Environment
1. Chrome Version 43.0.2357.132 (64-bit)
2. OSX Yosimitee 10.10.4 (14E46)

![screen shot 2015-07-30 at 4 14 41 pm](https://cloud.githubusercontent.com/assets/5209650/8993953/539f1c02-36d6-11e5-9e4b-a6233bf88043.png)
![screen shot 2015-07-30 at 4 14 28 pm](https://cloud.githubusercontent.com/assets/5209650/8993954/55c5b31a-36d6-11e5-8b88-2c79eef4caf1.png)
![screen shot 2015-07-30 at 4 15 15 pm](https://cloud.githubusercontent.com/assets/5209650/8993957/5953cfd0-36d6-11e5-8430-cba6635404d1.png)

**Comment by adamjohnson** [comment]
@jmarkle825 Would you mind editing your issue to follow the [Contribution Guidelines](https://github.com/wvuweb/cleanslate-cms/blob/master/CONTRIBUTING.md)? This will help us debug your issue.

I have seen this happening when we were working on the admissions site. A hotfix/workaround might be something like this:

``` css
img { 
  max-width: auto; 
  height: auto; /* You might need an !important here OR play with the specificity of the selector. */
}
```

Before any initial testing, I suspect this is getting inserted after a change in Chrome's `contentEditable` specification/support.

Related to #2.

**Comment by jasonmarkle** [comment]
I will give that a shot and see if it work. Will update in the AM or later tonight.

**Comment by nreckart** [comment]
The image height/width styles should be gone from any newly inserted images.

**Comment by jasonmarkle** [comment]
Ok, so that's a start, but should it really be putting any style tag in there at all? What need of inline styling do we have to justify that? Ditch it yo. 
![screen shot 2015-08-05 at 8 28 13 am](https://cloud.githubusercontent.com/assets/5209650/9085597/2991180a-3b4c-11e5-8d77-91d14527eb18.png)

**Comment by adamjohnson** [comment]
Just to follow up, @nreckart closed this issue because it solved the original problem. Jason's comment above refers to #2.
