### ISSUE TITLE
Changing to a repo with different template names causes internal service request errors

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#184]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Open a site > Settings > select theme (in this instance I went from Engineering: Faculty Research > Engineering: Center for Alternative Fuels Engines and Emissions)
3. Pages > Hover on a page that has a backpage template and select properties
## Results

Internal Server Request Error
## Expected results

Allows me to pull the properties panel up and select a new template since the default template does not exist.
### Environment

Operating System... Macintosh OS X 10.10.5
Screen Resolution...2560 x 1440
Web Browser...........Chrome 46.0.2490.80
Browser Size...........2200 x 1274
IP Address..............157.182.40.201
Color Depth.............24
Javascript................Enabled
Flash Version..........19.0.-1
Cookies...................Enabled
User Agent          Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5)
                                AppleWebKit/537.36 (KHTML, like Gecko)
                                Chrome/46.0.2490.80 Safari/537.36

![Image of Issues in cleanslate](http://i.imgur.com/TmQq2jW.png)

**Comment by nreckart** [comment]
This should be fixed. @jasonmarkle can you verify?

**Comment by jasonmarkle** [comment]
Tested and verified. The expected result is now occuring. Closing the issue. Thanks @nreckart !
