### ISSUE TITLE
Issue: link to cleanslate in footer

### ISSUE THREAD

**Issue by ldbridges** [wvuweb/cleanslate-cms#189]
On concept board it was requested that the color of the footer link to cleanslate (date link) not be a different color. Should this be fixed on the patterns? I've had this mentioned a few times being it's a security issue.

**Comment by adamjohnson** [comment]
Lisa: issues involving Patterns should be filed in the [Brand Patterns](https://github.com/wvuweb/brand-patterns). Also, this issue has already been resolved. See this issue for more info:

https://github.com/wvuweb/brand-patterns/issues/21

If you are copying and pasting themes that you've done in the past, you won't get the updates that we've pushed to Brand Patterns. You'll have to build a theme "from scratch" if you want those updates or you'll have to merge changes from Brand Patterns into your theme manually.
