### ISSUE TITLE
Reuse Content Snippet - Updated Content

### ISSUE THREAD

**Issue by dustinmazon** [wvuweb/cleanslate-cms#190]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Select the your site.
3. Create a page called "page A", load content into an editable region and publish.
4. Create a new page called "page B" and use the "reuse content" snippet to populate an editable region and then publish.
5. Update "page A" editable region content.
6. Notice the difference between versions of "reuse content". 
## Results

The "Reuse Content" snippet gets out of sync with the original editable regions content if it is updated. 

Page A:
![screen shot 2015-11-12 at 1 33 52 pm](https://cloud.githubusercontent.com/assets/1126703/11127489/917f3372-8942-11e5-9c0f-a4e0a61ee784.png)

Page B: 
![screen shot 2015-11-12 at 1 30 57 pm](https://cloud.githubusercontent.com/assets/1126703/11127492/96f6e3ae-8942-11e5-993a-7fb603aa0f61.png)

Notice Page A has new styles and formatting that didn't show up on Page B. 
## Expected results

It would be nice if the "Reuse Content" snippet automatically updated the content based on changes made and published to the original editable region.

**Comment by nreckart** [comment]
Wait 15 to 30 minutes then look again.
