### ISSUE TITLE
Feature Request: Easy Access to Files URL

### ISSUE THREAD

**Issue by bokster** [wvuweb/cleanslate-cms#191]
There is no easy way to retrieve links of PDFs or images for public viewing/download. Current method is to add a link to some text on a page via Insert Link and then hover it to get the URL.
## Proposal

Perhaps adding a "URL" in the file property.

![pdf](https://cloud.githubusercontent.com/assets/289061/11511547/b7cc68b6-9837-11e5-8f67-68b83adf2769.png)

**Comment by nreckart** [comment]
For now, I added the public URL for a file to its edit form/modal. There's probably a better place to display it in the long term, but after some internal discussion we decided on the form for now.

Keep in mind that the public URL is based on the current default/primary domain for the site. So if you're working with a new site via a sandbox URL, it's going to change when you move to production.

**Comment by adamjohnson** [comment]
![file-public-url](https://cloud.githubusercontent.com/assets/575865/11826167/8e2c6b76-a351-11e5-946e-9a4f4e9f26bd.png)

Here's a screenshot of this. I'm going to close this issue for now. We can re-open it if needed in the future when we get more file properties/meta info.

**Comment by bokster** [comment]
Cheers!

**Comment by bokster** [comment]
A client, who is using a PC, says she is unable to copy and paste the URL in Firefox (Chrome is fine). I am able to duplicate the issue on a PC. I've asked her to use Chrome in the meantime.

Also, she seems to think that the URL cannot be copied initially because of the "you-cannot-do-that" icon when she hovers on it.

![screenshot](https://cloud.githubusercontent.com/assets/289061/12793756/fcf0e91a-ca7f-11e5-8dd6-cd098a3e8623.png)

**Comment by adamjohnson** [comment]
@zeroedin suggested we use the `readonly` attribute instead of `disabled` for this field. Here's a demo: 

http://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml_input_readonly

:+1:

**Comment by nreckart** [comment]
Did as @zeroedin suggested and made it readonly. Should work now.

**Comment by bokster** [comment]
Thanks everyone.
