### ISSUE TITLE
Labels cant be edited after creation

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#192]
Labels that are already created and saved to the CMS will not allow themselves to be edited even if the user has admin privileges or is the site owner.
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Click Labels > Attempt to edit a label and save. Try with and without the checkbox selected.
## Results

Produces a 'Request Failed (Forbidden)' error
## Expected results

It's supposed change the label at a global usage level
### Environment
1. OSX 10.10.5 (14F27)
2. Version 46.0.2490.86 (64-bit) 

![Image of issue with labels not being editable](http://i.imgur.com/vx5Zcgd.png)

**Comment by jasonmarkle** [comment]
I'll go ahead and mention this is low priority obviously. It's simpler to just create a new label, but I felt this was not working as intended and didn't want to forget about it.

**Comment by nreckart** [comment]
This should be fixed.

**Comment by jasonmarkle** [comment]
confirmed. issue has been resolved.
