### ISSUE TITLE
Calendar as a snippet

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#193]
So this might be easily accomplished with a radius snippet for the time being, but, how about we maybe consider adding the calendar as a snippet. My situation follows, and hopefully other people deal with this as well:

On our main site we have a calendar feed, that feed isn't the same as the one on the department pages, and each department has their own feed, which are all different as well. So that's like 10 feeds, which means 10 of the same pattern where you are only replacing the calendar ID.

What if we took this as a snippet, inserted into an editable region within a template theme that is on a site, and only needed to plug in the calendar ID. You have all 10 calendars done with the same theme (ex all your college level departments) and you don't need to bulk up the repository and have 20 different views because one thing is different, but essentially the same on every site.

Thoughts? Let me know if this can be accomplished with a radius tag in the short term, but I feel the calendar is so widely used at all levels of the university, a dummy proof snippet would be nice to integrate.

**Comment by adamjohnson** [comment]
The calendar needs to be set up from a theme perspective (requires jquery and CSS), so we're not going to make a snippet for it. You can insert it into an editable region via the "Radius Snippet" if it needs to be editable and set `scope="site"` if you need to.

Alternatively, if the calendar feed changes per page, you could use (again) a normal editable region with the "Radius Snippet" _or_ custom data and have the custom data key be the calendar category ID. And, if you only have one calendar category ID per theme, you could put the embed straight into the template.

@jja006 has also informed me that the way calendar embeds work with the new calendar will change, further complicating a snippet for it (do we update the snippet? do we make a v1 and v2? Bonk!).

**Comment by jasonmarkle** [comment]
:+1:  I have done this and it makes it way easier just throwing the JS in to the radius snippet. Especially when using a repo that might have templates that span multiple sites.

**Comment by adamjohnson** [comment]
An even better way to do this would be to use a Custom Site Data Attribute. They're new as of yesterday, 12/17/15. Here's the docs for `custom_site_attributes`:

http://cleanslatecms.wvu.edu/how-to/theme-development/custom-data#How_to_use_Custom_Site_Data_attributes_49

Using `script` tags inside the Radius Snippet has been hit or miss in the past, so using Custom Site Attributes are probably a better way to go about doing that.
