### ISSUE TITLE
Undefined Tag 'previous_url'

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#194]
## Steps to reproduce the issue
1. Log in to a cleanslate site with pagination on the blog
2. Push an update to the repo
3. In cleanslate go to Manage > Messages
## Results

It does this.

Gives me an error about the previous_url tag being undefined

It's supposed to do this.

There should be no error, as previous_url is a defined tag https://github.com/wvuweb/brand-patterns/blob/master/views/blog_index.html#L45
### Environment
1. osX 10.10.5 (14F27)
2. 47.0.2526.80 (64-bit)

[img](http://i.imgur.com/kA1UkjB.png)

**Comment by nreckart** [comment]
In the future, please provide the URL that generates the error along with the site and theme being used.

This URL is generating the error: http://statler.sandbox.wvu.edu/news/images/show-search-icon-blue.svg

This isn't even a valid URL, so it should be throwing a 404, which is a separate issue that I will need to look into. Where is this URL being generated/used?

The `previous_url` is working fine on http://statler.sandbox.wvu.edu/news.

**Comment by jasonmarkle** [comment]
Sorry about that:

URL: http://statler.sandbox.wvu.edu/news

Template: https://stash.development.wvu.edu/projects/CST/repos/engineering/browse/views/blog_index.html

Correct-URL: http://statler.sandbox.wvu.edu/images/show-search-icon-blue.svg

So here's a watered down version of what's happening.

The css has a relative file path to the image location, and on any typical page it would be throwing out the image perfectly fine because the css is looking in url/images/image-file.whatever

For some reason though, the blog-index wants to throw it's page name into the mix, and you suddenly get url/page-name/images/image-file.whatever, which is always going to be an invalid link.

**Comment by jasonmarkle** [comment]
Also to note, that css is in the cleanslate CSS under the settings. I'm inlining the style to overwrite the colors and then pull those two images in so that it doesn't require a pattern every time someone wants to change stuff to a different color. This could also be part of the problem since that get's inlines in the head of the page. And actually, now that I think that could be the main cause since it's not an actual stylesheet.

This however has not been an issue on other sites, such as http://methanestudy.sandbox.wvu.edu/home

**Comment by nreckart** [comment]
Yes, using a relative image path in the site CSS that way is most likely the issue. CleanSlate does some special processing of relative file URLs within the theme CSS to ensure they are valid. That processing does not get done on the site specific CSS.

**Comment by jasonmarkle** [comment]
Confirmed. There have been no additional errors since using an absolute path. For some reason, at the time, a relative path didn't seem like a big deal. Hindsight is always 20/20 I guess. It should have been an absolute path from the start simply because it's being embedded in to a `<style>` tag, so this is not a bug and I'm closing the issue.
