### ISSUE TITLE
Suggestion: single column list for custom data

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#196]
Essentially, we have a two column list for the custom data, but due to how custom data handles naming conventions with either underscores or camel case really being the best formatting options maybe we should break this in to a single column with the input fields floating to the right margin and the naming conventions to the left.

Currently, having the two column list forces long strings to fall behind the input field which could be confusing to other users working in the CMS. I realize the system could handle regular verbiage, which would really be the most convenient output, but then that potentially ignores existing system limitation it feels like. Could an option for a custom data field alias be integrated in to how custom data is handled in the config.yml file and page templates? ex: `-nameOfYourData (Alias displayed to user in parens)`

Operating System    Macintosh OS X 10.10.5
Screen Resolution   2560 x 1440
Web Browser Chrome 47.0.2526.80
Browser Size    2334 x 1274
IP Address  157.182.40.201
Color Depth 24
Javascript  Enabled
Flash Version   20.0.-1
Cookies Enabled
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36

![Imgur](http://i.imgur.com/uqRWQ57.png)

**Comment by adamjohnson** [comment]
The following two commits fix this issue:

https://github.com/wvuweb/cleanslate/commit/fc2077e1433810fad1e7c3de1dfe3ff6ab86f033

https://github.com/wvuweb/cleanslate/commit/0bec817c0ae1a79f23dd5e6edec2836789929b2e

Here are two images of the new custom data layouts:

![custom-site-data-layout](https://cloud.githubusercontent.com/assets/575865/12152788/6c6f158a-b484-11e5-8bdd-9d507b5b12a1.png)

![custom-page-data-layout](https://cloud.githubusercontent.com/assets/575865/12152796/711eeb82-b484-11e5-9c8c-0dc7398a8f7f.png)

The custom data name/key is now on top. You'd have to have one hell of a long name/key to have that wrap.

Edit: as of 1/6/15, these changes haven't been deployed to production; however, they have been committed and should show up in production shortly.
