### ISSUE TITLE
Don't allow users to create pages with the same permalink

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#197]
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Go to a site then Pages.
3. Create a page called "Nathan Reckart". Make sure the permalink is `/nathan-reckart`. Also, be sure there is not already another page with this exact permalink.
4. Now that you've created a page with the permalink `/nathan-reckart`, create the page again. Call it "Nathan Reckart" with the permalink of `/nathan-reckart`. You now have two identical pages with identical permalinks, `/nathan-reckart`.
## Results

The system allows you to create two identical pages. If you try to visit those pages, one of them will send you to the homepage.
## Expected results

Users should not be allowed to create two (or more) identical pages of any kind (Content, Blog Index, or Blog Articles).
### Things that might help:

An inline error could show with the following message:

> Uh oh! This permalink already exists in your site. Please use a different permalink. 

If you wanted to get fancy with your error message, [Bootstrap Modal](https://github.com/jschr/bootstrap-modal) comes with a `.shake` class that allows you to "shake" the modal to say no. Here's the class:

https://github.com/jschr/bootstrap-modal/blob/master/css/bootstrap-modal.css#L209

They have this implemented in the Bootstrap Modal demo [here](http://jschr.github.io/bootstrap-modal/). Search the page for "shake". That will take you to "Static Background with Animation". Click the "View Demo" button. Instead of clicking any of the buttons, click anywhere outside of the modal. The modal window will then shake. 

[This](https://eltimn.github.io/jquery-bs-formalerts/) might be helpful to display inline form errors. If you already have something for that, please ignore me. 
#130 is somewhat related to this.

**Comment by nreckart** [comment]
Related to #204 and fixed with it.
