### ISSUE TITLE
Feature Request: Expiration Date for articles

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#198]
For me in particular this would be to just help with the massive amount of news that we push. The ability to set an expiration date within the articles page options, or better yet even all pages if we have some sort of event promo splash or landing page, would be a tremendous help in content management for blog posts, event campaigns or job listing. I can see this being well used at a higher level for other colleges as well who might generate a lot of content that doesn't need to stay in their system for a huge period of time (like < 12 months).

My initial thought is that you could have the option to set the expiration date, and either set it to delete, or go to an archive of some sort in case you need it again later, with the default option being archive. 

I'm sure this idea could be elaborated on more, so I wanted to get the thoughts and conversation flowing so that anyone else that thinks this would be useful can chime in as well.

**Comment by adamjohnson** [comment]
Have you seen this issue?

https://github.com/wvuweb/cleanslate-cms/issues/168

**Comment by jasonmarkle** [comment]
@adamjohnson I did not, thanks for the reference!
