### ISSUE TITLE
absolute file paths for images when using rss and xslt

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#200]
This issue was discussed via email with @nreckart 

Would like to see a way to output absolute file paths of images when using rss and xslt. This would allow the user to pull in an image from a blog in the blog.rss and output it to another site using an xslt stylesheet.

Initial code in blog_index.rss
`<description>
     <![CDATA[
     <img src="<r:article:content name="article-media__first" />" 
     height="768" 
     width="1024" /> ]]>
    </description>
`

Currently, the xslt will only supply a relative file path to the image when using radius tags, causing it to break since the file isn't located on that site.

Input:
`<xsl:template match="item">
    <li>
      <div class="item-description">
        <xsl:value-of disable-output-escaping="yes" select="description"/>
      </div>
    </li>
  </xsl:template>`

Output:
`<div class="item-description"> 
     <img src="/resource-not-found-on-this-site-418" a="" portrait="" of="" john="" hu="" next="" to="" the="" flying="" wv="" data-asset-id="28991" data-asset-version="876x493">"  height="768"   width="1024" /&gt; 
    </div>`

**Comment by nreckart** [comment]
You can now specify `absolute_urls="true"` in the `<r:page:content>` tag(s) used in the blog RSS template, which will then use absolute URLs for all internal URLs, which includes images, page links, and file download links.

`<r:page:content name="region_name" absolute_urls="true" />`

I had originally planned to just make the change globally and always use absolute URLs, but then I realized why I didn't do that from the beginning. Things get complicated and break down when editing a page. So doing it explicitly will have to suffice for now.

**Comment by jasonmarkle** [comment]
I'll try to confirm this later this afternoon. Letting the dust settle right now with everyone going to their new sites and check on their stuff.

**Comment by adamjohnson** [comment]
Should this change be implemented for brand-patterns [default RSS template](https://github.com/wvuweb/brand-patterns/blob/master/views/blog_index.rss)? Here's [the code](https://stash.development.wvu.edu/projects/CST/repos/code/browse/views/_blog_index--v1.rss). Or is this change specific to @jasonmarkle's use case?

Make the case for and against.

**Comment by nreckart** [comment]
@adamjohnson yes, after we confirm that things are working as expected. Without it, all URLs for internal resources are broken when pulled into external sites via the RSS feed.

**Comment by jasonmarkle** [comment]
@adamjohnson The biggest issue of this was that it needed done to pull in images primarily, which is why the absolute file path was needed. Prior to this, you could get the relative file path output with `<description>` however, the `<media:content>` tag wouldn't return any output, and that reduces flexibility since having multiple description tags will not pass validation. So maybe we should brainstorm on how to handle alleviating that at some point for the long term fix? [http://help.campaignmonitor.com/topic.aspx?t=277](url)

**Comment by nreckart** [comment]
Huh? Like I said, as it stands now, all internal URLs that appear in RSS feeds for every site that has an RSS feed in CleanSlate is broken. That includes image source URLs, page URLs, and file download URLs. So the actual problem described by this issue goes beyond just images.

You can see a perfect example of this in the current [RSS feed](http://statler.wvu.edu/news.rss) for the new Statler site. The "WVU Engineers Week to feature lectures, prizes, competitions" article includes an 'Engineers Week' link, which is incorrectly linked to a CleanSlate editor URL.

`<media:content>` has nothing to do with CleanSlate. It is just an XML element. How it's handled depends on whatever is using the RSS feed.

**Comment by adamjohnson** [comment]
I've made RSS feeds that pull from the `code` repo in Stash output absolute URLs. Here's the relevant commit:

https://stash.development.wvu.edu/projects/CST/repos/code/commits/4d7956c9698b8816f38182d0d57d68643302fcaf
