### ISSUE TITLE
Article Count in r:blog

### ISSUE THREAD

**Issue by bokster** [wvuweb/cleanslate-cms#202]
Currently the number that is showing the number of articles looks like it's part of the date. Maybe we can wrap it inside a parenthesis, i.e., February 2016 (30)? 

![screen shot 2016-02-08 at 2 13 58 pm](https://cloud.githubusercontent.com/assets/289061/12896293/369e0736-ce6f-11e5-8594-fc1a6fdd51cb.png)

**Comment by adamjohnson** [comment]
You can control this via CSS. Here's an example:

https://stash.development.wvu.edu/projects/CST/repos/honors-college/browse/scss/partials/_blog.scss#14-15

Here's the docs on how to add a custom class to those numbers: http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-blog-attr
