### ISSUE TITLE
Add "Enhanced Link Attribution" to default Google Analytics code

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#205]
When reporting on landing pages and campaigns it would be good to be able to determine which links on a page a user clicked on. Right now GA only tracks that User A visited Page Z from Page Y. When looking at Page Y all of the links on that page have the same "click through" percentage. Adding link attribution would let us distinguish traffic between links. More info:

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution

Can I get a +1 for this issue from someone else? Just want a sanity check before we implement.

**Comment by zeroedin** [comment]
+1

**Comment by dmolsen** [comment]
Dear Nathan,

Can you update the `html_injector` to support this attribute, please? `ga('require', 'linkid');` should go between lines 10 and 11. No rush. Danke.
