### ISSUE TITLE
Twitter Platform JS

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#207]
Let's reevaluate if we need to have the Twitter JS included in every request. I don't believe we need it for Admissions but I'm seeing it in our requests in Speedcurve. I'm assuming this is an `html_injector` thing.

**Comment by adamjohnson** [comment]
:+1: 

I think this came from the introduction of the Twitter Snippet. Much like Flexslider, themes can be set up to include the Twitter JS or maybe it could be included if the snippet gets added to the page or if there are any snippets on the page.

**Comment by nreckart** [comment]
@dmolsen Interesting find. The Twitter JS is indeed added by the HTMLInjector, but it's only supposed to be doing it if one or more `//a[class='twitter-timeline']` exists on a page. Looks like that logic is flawed and it's always adding the JS. I'll fix it.
