### ISSUE TITLE
Limit Ability to Delete Default Page

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#208]
We had an issue where a user deleted their home page but did not have the permissions to select a new one. In order to address this in the future I think we can go in two directions:
1. limit ability to delete a default page to those permission levels that have access to "settings." "writer/publisher" definitely doesn't have that level as I logged in as the user in question.
2. don't allow anyone to delete the default page until a new default page is selected. credit to @zeroedin for this idea.

I think option 2 is better but what do other people think?

**Comment by nreckart** [comment]
I vote like I originally did. No deleting of any pages allowed by anyone ever.

**Comment by dmolsen** [comment]
![ ](http://i.giphy.com/FmijXcVr53g2I.gif)
