### ISSUE TITLE
Add support for  by="alternate_name"

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#211]
There is current support for by="name | slug | created_at | updated_at | published_at | sort_order |  template_name" but "alternate_name" is unsupported.

Due to things I've worked on, I'm partial to the idea of support for alternate_name, as I want to display the person's name in a directory listing but still sort by last name (which would be the alternate name in this case)".  I'm hopping that the XML/XSLT will get implemented in to the out-of-the-box patterns sometime within the next month or two as I refine things, so it would be nice if developers had the extra support so they can sort by name or alternate_name depending on what's best for their users or the size of their directory.

Completely open to other thoughts or comments on this as well and possible use cases.

**Comment by nreckart** [comment]
It is now possible to sort pages by "alternate_name" as well as by "title" and "meta_description". Not sure how useful that last one will be, but it's now possible.
