### ISSUE TITLE
Add sever side support for GA async filtering 

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#213]
Right now, GA will effect page load by a small percentage. In order to alleviate that we could implement `ModPagespeedEnableFilters make_google_analytics_async` on the server. 

[Make Google Analytics Asynchronous](https://developers.google.com/speed/pagespeed/module/filter-make-google-analytics-async)

**Comment by jja006** [comment]
Closing as this was marked as invalid.
