### ISSUE TITLE
is_site_default and is_not_site_default Tags

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#218]
I currently have a bad hack in the Undergraduate Admissions theme to modify the title tag and canonical tag. It's using the page title to determine what page is the default page for the site and modifying content. It looks like:

```
<r:set_var name="pagetitle"><r:page:first_non_blank_attr names="title, name" /></r:set_var>
<r:if value1="{$pagetitle}" value2="Home" operator="=">
      <title><r:site:name /> at West Virginia University</title>
      <link rel="canonical" href="https://<r:site:domain />">
</r:if>
<r:if value1="{$pagetitle}" value2="Home" operator="!=">
      <title><r:page:first_non_blank_attr names="title, name" /> - <r:site:name /> at WVU</title>
      <link rel="canonical" href="<r:page:url https="true" />" >
</r:if>
```

which outputs:

``` html
<title>Undergraduate Admissions at West Virginia University</title>
<link rel="canonical" href="https://admissions.wvu.edu">
or
<title>How to Apply - Undergraduate Admissions at WVU</title>
<link rel="canonical" href="https://admissions.wvu.edu/how-to-apply">
```

I'd like to suggest these as a change to the Super Theme. There's no real reason to have "Home" in the title of the home page. It just mucks up the title in Google search results. `link rel="canonical"` seems to have improved search results. But looking for "Home" isn't the best solution. Can we add `<r:page:is_site_default>` and  `<r:page:is_not_site_default>` as tags to use instead? I think I'd use it in the following way:

```
<r:page:is_site_default>
      <title><r:site:name /> at West Virginia University</title>
      <link rel="canonical" href="https://<r:site:domain />">
</r:if>
<r:page:is_not_site_default>
      <title><r:page:first_non_blank_attr names="title, name" /> - <r:site:name /> at WVU</title>
      <link rel="canonical" href="<r:page:url https="true" />" >
</r:if>
```

I'm open to changing the tag names. Wasn't sure if "not" or "unless" would be better (e.g. "unless_site_default"). Didn't seem like there was a standard in looking at the tag index.

What do you think?

**Comment by nreckart** [comment]
Implemented `<r:page:if_site_default>` and `<r:page:unless_site_default>`

Usage:

```
<r:page:if_site_default>
  This is the default page
</r:page:if_site_default>

<r:page:unless_site_default>
  This is NOT the default page
</r:page:unless_site_default>
```
