### ISSUE TITLE
Add a tag to inline a stylesheets content directly into html.

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#220]
This is a request to add a tag that will take the css from a stylesheet and inline it's content directly into a place within an html document using a radius tag (ie. `<r:inline_stylesheet name="foo.css" />`)

Unfortunately `@import` works the same way as <link> does, and blocks rendering of the page.  Currently this is being alleviated with a JS function that loads the primary styles.css file asynchronously. Because of this, the content initially shows to the user completely unstyled for a moment. To alleviate this, we can use critical CSS.

Critical CSS is a method of inlining styles in a `<style>` tag so that as the HTML loads and the CSS file gets loaded Asynchronously, the site can still present above the fold content to the user appropriately styled. In order to accomplish this, the above suggested tag would output the file content of a css file appropriately named something like "foo" inside of a `<r:yield name="critical">` tag which could then be pulled from the template to the head of the document. 

It would be template specific so that only the correct styles are loaded, using multiple stylesheets that can be managed via gulp. This prevents the need to output the file, then copy and past the content in each template's yield tag every time a change is made to one of the scss files.

This also helps both site performance, as well as user experience with slower connections, and would make workflow extremely manageable for all sites that we apply this method to in the future, which will likely be a lot of them.

**Comment by nreckart** [comment]
@jasonmarkle Do you want the CSS wrapped in `<style></style>` tags when output? Or just the CSS and you can wrap it in whatever you want?

**Comment by jasonmarkle** [comment]
@nreckart just the css and then it can be wrapped by the user in whatever. That way we can still manually output things like the hero image with additional css in the `<style>` tag as well.

**Comment by nreckart** [comment]
Implemented the `<r:stylesheet_content>` tag.

Usage: 

```
<style>
  <r:stylesheet_content name="fancystyles.css" />
</style>
```
