### ISSUE TITLE
Internal link content...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#226]
If I am looping through a set of pages, can there be a way to check if one of the pages is an internal link, then, if it is grab content from that internal page? For example, I have a pattern that loops through a set of child pages and grabs a thumbnail image for each page, then displays the thumbnail in a list. But internal links have no content regions, so there will be a blank spot for the thumbnail when that 'page' is displayed. See here: http://extension.sandbox.wvu.edu/lawn-gardening-pests/lawn (the Lawnmower Safety feature). They are using an external link for that particular feature because that page exists in a different place in the site structure and needs to be shown in 2 different places.

**Comment by adamglenn** [comment]
An alternative solution to this would be to enable custom data for an internal link. Then maybe I could add a thumbnail or a page ID to grab content?

**Comment by nreckart** [comment]
@adamglenn There is currently no way to determine if a page is an internal link from within a template. Would it be possible to build this thumbnail list using a label to mark all of the relevant pages and something like `<r:root><r:descendants labels="lawn-nav">...` as a work around for the time being?

**Comment by nreckart** [comment]
Did you find a solution for this?

Custom data is (should be) supported for internal link pages, but since they have no template associated with them, you'd have to define the attribute(s) in the theme config.yml file with the `custom_data_attributes` key. This would make them available to all pages in the site.

**Comment by adamjohnson** [comment]
I'm closing this issue. @adamglenn feel free to open it back up if you feel it's needed.
