### ISSUE TITLE
Labels in CleanSlate are concatenating in to a single string

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#227]
Existing content with labels in CleanSlate are concatenating those labels in the page properties. If an edit is made, and that concatenation is overlooked by the publisher, it wrecks their content if those labels are being utilized in ways to pull content.

## Steps to reproduce the issue

  1. Log in to CleanSlate.
  1. Go to a site like WVU Today (their PT is who reported this initially).
  1. Under their stories page, open up the page properties for a child page.
  1. Note that the labels are listed properly on the right hand side, but concatenated into a single string in the page properties "Label" field.

## Results

Publishing will concatenate the labels into the single string. You can add new labels to fix the issue until you go back in to edit the page again. 

## Expected results

Each label should be staying independent from their other counterparts.

### Environment

1. Operating System
Macintosh OS X 10.12.4
3. Screen Resolution
1920 x 1080
5. Web Browser
Chrome 57.0.2987.133
7. Browser Size
1592 x 776
9. IP Address
157.182.64.13
11. Color Depth
24 bit
13. Javascript
Enabled
15. Flash Version
Not Installed
17. Cookies
Enabled

**Comment by nreckart** [comment]
Fix has been deployed. Fixed in wvuweb/cleanslate@474dcb24d4c1184.
