### ISSUE TITLE
Calendar Feed snippet seems to be broken...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#228]
When I past in the feed and click "Insert" nothing happens.

**Comment by nreckart** [comment]
Fix and deployed in wvuweb/cleanslate@de0dbb70edb86c.

**Comment by nreckart** [comment]
Editing an existing calendar snippet was broken after the the updates in wvuweb/cleanslate@de0dbb7, throwing an invalid URL error. Fixed in wvuweb/cleanslate@d05977a8c5b1.
