### ISSUE TITLE
Blog archives are generating a .0 after dates (global issue)

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#229]
Just see the following. Not sure how I could replicate this outside of just making a new blog somewhere.

Head over to one of these news areas and then click on any of the archive links:

[http://eberly.wvu.edu/news-events/eberly-news](http://eberly.wvu.edu/news-events/eberly-news)
[http://www.statler.wvu.edu/news](http://www.statler.wvu.edu/news)

**Comment by nreckart** [comment]
Fix has been deployed. Fixed in wvuweb/cleanslate@146f7240758d5d.
