### ISSUE TITLE
Pages are returning a 404 not found without the error page on existing pages

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#230]
Navigate to the NRCCE site.
Go to pages.
Under the media page there is a child page called "NRCCE in News".
View the page

You get a 404

Ideally you would see the content of the page.

This is happening on some other pages as well according to the PT up there.
You can access the page via edit mode and it's just a plain backpage. Also no data in any of the custom data fields.

**Comment by nreckart** [comment]
/media/* does not appear to be a valid URL for CleanSlate pages. As far as I can tell it isn't specifically reserved for anything by the app. I'm guessing it's getting intercepted by Apache somewhere. Haven't been able to determine where/how yet.

For now, you can fix it by changing the permalink/slug of the "Media" page to something other than "media". I changed it to "in-media" and everything works as expected. 

http://nrcce.sandbox.wvu.edu/in-media/nrcce-in-news

They can change it to whatever they want. I'll have to dig deeper to find out where exactly /media is getting intercepted.

**Comment by nreckart** [comment]
Should be fixed now. Something in the app was indeed hijacking '/media/*' URLs. I changed the NRCEE Media page slug back to 'media'.
