### ISSUE TITLE
Publish > Unpublish > Publish content bug

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#238]
## Steps to reproduce the issue

  1. Go to a page, publish some content.
  1. Go back to Pages in CleanSlate and hit "Unpublish" to the page from step 1.
  1. Edit the same page. Add some new content. Save (but do not publish) this page.
  1. Return to Pages in CleanSlate and hit "Publish".

## Results

The content on the page shows what was last published.

## Expected results

Since we added new content in step 3 and saved that content, hitting "Publish" should show us the new content.

_________________________

Found this when we were announcing the [Ultimate Mountaineer Fan](https://trademarklicensing.wvu.edu/fans/ultimate-mountaineer-fan) hat. I'd made a "Winning Hat" page and published it (with [fake hat images](https://trademarklicensing.wvu.edu/files/d/e5b5da3c-862e-408d-8834-9d0daa47f304/baseball-hat-clipart.png)) to make sure everything was groovy. Then, I unpublished the page so no one could hit it.

Several days later, we added real content to announce the winners. When we went to publish that page, I hit "Publish" via Pages and it showed the fake hat images + old text content instead of the winning hat and new content.

This tells me hitting "Publish" in Pages is different from hitting "Publish" in the editor.

**Comment by nreckart** [comment]
@adamjohnson You are correct. Publishing a page from the site tree admin view only publishes the page, which basically means setting the published_at date. Publishing from within the editor publishes the content of the page, and in turn, the page itself.

Makes sense that they should behave the same. I'll look into it.
