### ISSUE TITLE
Publishing / unpublishing via the page manager deletes custom page data.

### ISSUE THREAD

**Issue by architarious** [wvuweb/cleanslate-cms#239]
- Using the publish / unpublish function via the page manager will delete that pages custom page data. 
- Publishing via the content editor doesn't reproduce this bug however. 
- This bug didn't exist until fairly recently (within the last two weeks). 
- Was able to reproduce this bug on multiple sites, including super-theme sites.

## Steps to reproduce the issue

1. Find a page with custom page data (page manger > properties > custom data)
2. Click unpublish or publish from the page manager
3. Custom page data is gone

**Comment by nreckart** [comment]
This issue was introduced when moving to strong parameters in prep for updating the Rails framework a few weeks back.
