### ISSUE TITLE
gif Issue with Sizing in url

### ISSUE THREAD

**Issue by msmoirai** [wvuweb/cleanslate-cms#242]
## Steps to reproduce the issue

  1. Log in to CleanSlate.
  1. Selected media to add image to page.
  1. Choose image
  1. Upload File
  1. Add Files
  1. Selected the .gif I wanted to add
  1. Open
  1. Start Upload
  1. Closed Upload Files
  1.  Saw that the gif images appear broken
  1. Chose gif anyway
  1. Added alt text
  1. Insert Image

## Results

Gif image shows as if the multiple frames are being duplicated

## Expected results

Gif image shows normally with animation

### Environment

Operating System Mac OSX 10 (Unknown Version)
Web Browser Chrome 67.0.3396.99
Screen Resolution 1600 x 900
Browser Size 1599 x 780
Javascript Yes
Cookies Yes
Color Depth 24
Flash Version Not Installed
IP Address 157.182.40.201
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X
10_13_5) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by adamjohnson** [comment]
Michelle, would you mind editing your issue to follow the format from our [Contribution guidelines](https://github.com/wvuweb/cleanslate-cms/blob/master/CONTRIBUTING.md)? This will help Nathan properly recreate your issue, step by step, and see exactly what you're seeing.

**Comment by nreckart** [comment]
This doesn't appear to be an issue anymore. It may have gotten fixed along with the move to Lambda for image processing.
