### ISSUE TITLE
Page filtering sort columns

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/cleanslate-cms#243]
## Steps to reproduce the issue

  1. Log in to CleanSlate.
  1. Click Pages -> Advanced Filter
  1. Filter by any options.

## Results

Pages return ordered by Last Edited. 

## Expected results

It would be super awesome if pages could be returned with Created On / Published On column, and also sortable on all columns [Except page path and Labels].

Slightly unrelated, but im not sure Page path is useful in this view, so that could most likely be removed to gain space for the extra 2 date columns?  

### Environment

  1. Cubeville

**Comment by nreckart** [comment]
Page path is needed because there are sites with 50 pages named exactly the same. I believe the path was added for that exact reason, by request. The path lengths can get insane, so moving it out of the grid and maybe displaying it below the column data, full width, would help.

**Comment by nreckart** [comment]
I think the main point of this issue, sorting page results, has been addressed.
