### ISSUE TITLE
Support for <r:article:template:name>

### ISSUE THREAD

**Issue by architarious** [wvuweb/cleanslate-cms#245]
## Suggestion

We currently have the ability to use tags like `<r:page:template:name />` to output the name of the pages template, however this doesn't work on blog articles. 

It would be nice if this functionality was carried over to articles as `<r:article:template:name />`.

## Use Case

At the moment, the most efficient way to style or filter different kinds of articles within a blog index is to use labels/tags, which some content editors forget to add. If we could simply tell which template an article is using we could utilize conditional logic to create unique views within a blog index and not have to worry about missing labels.

**Comment by nreckart** [comment]
Since articles are really just normal pages with some additional features/behaviors, you can just use `<r:page:teamplate:name />` within the articles context. Same goes for most, if not all, of the other `<r:page:*>` tags.

**Comment by architarious** [comment]
Okay, yeah that worked. Thanks!
