### ISSUE TITLE
Custom data attributes default value doesn't take until you re-save...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#250]
When I set a default value to a custom data attribute, I have to go into the page properties after the page is created, then hit Save for the value to actually take. For example, in the SuperTheme I have a Profile template, with the attribute slot_1 set to the 'profile' component. But the actual profile component doesn't show until you go back in and save the properties. It would be nice if whatever is in the default custom data is automatically applied when the page is created. This is useful for Super Theme because it will allow the user to move the "profile" component (or whatever other components I set to display as default for various templates) to be moved around to create dynamic layouts, else just leave it there as the default for Slot 1 if they don't want to mess with it.

**Comment by adamjohnson** [comment]
@adamglenn is this issue a duplicate of #247?

**Comment by adamglenn** [comment]
Yes, it is. I do not remember creating the other issue LOL.
