### ISSUE TITLE
Internal pages not getting active class added to them in navigation

### ISSUE THREAD

**Issue by TatsuJohnson** [wvuweb/cleanslate-cms#251]
In a navigation, a page that is an internal link will not get the "active" class passed to it. This make it hard to stylize the link to show if it is the active page on a site or not.

**Comment by adamjohnson** [comment]
Tatsu, thanks for reporting this issue. Would you reformat your issue to follow the [contribution guidelines](https://github.com/wvuweb/cleanslate-cms/blob/master/CONTRIBUTING.md)? Doing this will help us troubleshoot your issue in a more timely manner.

Also please include what kind of navigation you're referring to (`r:site_menu`, `r:sub_menu` ...). Once you've made the edits, kindly follow up with a comment.

**Comment by adamjohnson** [comment]
I [can confirm](https://aj.sandbox.wvu.edu/backpage-1?1#active-test) that `active_class` works with `r:site_menu` when rendered within a Radius Snippet:

```html
<r:site_menu max_depth="1" active_class="tatsu-active" />
```

**Comment by TatsuJohnson** [comment]
## Steps to reproduce the issue

1. View a page in CleanSlate that has an internal link as part of its navigation bar. 
2. See if there are active styles that will show the user which top nav page they are using.  If so, continue to #3.
3. Click on a page in a navigation bar that is an internal link.

## Results

It does not display the same style for the internal link to identify where the user is on the top nav. This is because the “active” class does not pass onto this link.

## Expected results

The active class should pass into the internal site’s link. Then when on the link, the user can which top nav page is active due to the styling. 

### Environment

Any browser

You can visit this site as an example. https://designsystemcollege.sandbox.wvu.edu/home.  The Home page is styled so that there is a solid gold bar across the link to let the user know that they are on the home page. But when clicking on Profile or Program Page, the link does not display the gold bar.

**Comment by nreckart** [comment]
Issue has been fixed and deployed. @TatsuJohnson please confirm and close the issue accordingly.

**Comment by TatsuJohnson** [comment]
Thanks!
