### ISSUE TITLE
r:breadcrumbs tag should output link attributes

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#252]
## Steps to reproduce the issue

  1. Visit the [Downtown Campus Library](https://libraries.sandbox.wvu.edu/libraries/downtown) or [Bennett Tower Gallery - Housing](https://libraries.sandbox.wvu.edu/libraries/downtown) pages.
    a) NOTE: Both of these pages have the requisite link attributes specified via Page Properties ([Libraries Pages](https://cleanslate.wvu.edu/sites/852/pages) and [Housing Pages](https://cleanslate.wvu.edu/sites/623/pages) in CleanSlate).
  1. Run the [Siteimprove Accessibility Chrome Extension](https://chrome.google.com/webstore/detail/siteimprove-accessibility/efcfolpjihicnikpmhnmphjhhpiclljc).

## Results

It returns the "Link text used for multiple different destinations" WCAG A error.

## Expected results

The [`<r:breadcrumbs />` tag](https://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-breadcrumbs) should output the link attributes specified in Page Properties > Link Attributes.

![Link Attributes Modal](https://user-images.githubusercontent.com/575865/62876043-190e8400-bcf2-11e9-85e1-4695daac4158.png)

`include_link_ids` should default to `false` for the `<r:breadcrumbs />` tag.

cc/ @jetapia @ WVU Libraries.

**Comment by adamjohnson** [comment]
Relevant commits:

wvuweb/cleanslate@589e7247c38868c0b4e03f2d423d7db0e24b0684

wvuweb/cleanslate@cc3ae3126743f59df12e1027cb408f08015c5fd3

wvuweb/cleanslate@6b9d3d7e4319c18e150d49281677d2cd82986209

**Comment by nreckart** [comment]
The custom link attributes should now be applied to breadcrumb links as they are for the other menu tags. `include_link_ids` defaults to false, so templates will need to be updated in order for custom id attributes to be applied to the breadcrumb links.

Example:

`<r:breadcrumbs ul_id="main-breadcrumbs" ul_class="breadcrumb" include_link_ids="true" />`

**Comment by adamjohnson** [comment]
Youdaman! 💯 

I updated the docs for [breadcrumbs](https://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-breadcrumbs) on CleanSlateCMS.
