### ISSUE TITLE
r:breadcrumb should have an attribute to apply classes to links

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#253]
I want to be able to add utility classes to links in breadcrumbs to make it easier to use with new design system. so something like `<r:breadcrumbs link_class="text-white" />`.

**Comment by adamglenn** [comment]
Also, I assume this would allow me to pass in a variable, so `<r:breadcrumbs link_class="{$breadcrumbLinkColor}" />`.

**Comment by nreckart** [comment]
Would the class be applied to the `<a>` or the `<li>`?

**Comment by adamglenn** [comment]
The `<a>`.

**Comment by nreckart** [comment]
`link_class` is now a valid option for `<r:breadcrumbs>`

Example:
`<r:breadcrumbs ul_id="fancycrumbs" ul_class="breadcrumb" " link_class="super-fancy" />`

**Comment by adamjohnson** [comment]
I've added `link_class` to the [docs for `r:breadcrumbs`](https://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-breadcrumbs) on CleanSlateCMS.

AG: When you confirm this is working, kindly close this issue.

**Comment by adamglenn** [comment]
This actually doesn't work. What it does is apply an attribute of `link_class` to the breadcrumb html i.e. `<a link_class="whatever-my-class-is">`. Should output `<a class="whatever-my-class-is">`.

**Comment by nreckart** [comment]
@adamglenn This should be fixed. Can you verify and close?
