### ISSUE TITLE
Random Image snippet appears not to be working...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#254]
On the Talent and Culture site, Appreciation Across Campus page, the user has inserted a random image snippet, selected the label for 'breakfast' (which has been applied to 2 images) but nothing shows.

https://cleanslate.wvu.edu/sites/808/pages/90661/editor

**Comment by nreckart** [comment]
There was a 'Breakfast' label also, which was assigned to nothing and I think it was confusing things within the snippet. I deleted the unused 'Breakfast' label, and it seems to work now.

**Comment by adamjohnson** [comment]
@adamglenn is this issue resolved? If so, kindly close it. Thank you.
