### ISSUE TITLE
Pages > Internal Link > View/View in new tab broken

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#260]
## Steps to reproduce the issue

  1. Visit [my test site > Pages](https://cleanslate.wvu.edu/sites/5/pages).
  1. CMD + F for "An internal link page" (there is a page named this at the root)
  1. Click "View" or "View in New Tab"

## Results

The resulting URL is this:

https://aj.sandbox.wvu.edu71305/

Obviously, this leads to a 404 page.

## Expected results

The resulting URL should be:

https://aj.sandbox.wvu.edu/backpage-1/subpage1/subpage-level-3/a-target-of-an-internal-link-to-page

Clicking "View" or "View in new tab" should direct you to the appropriate URL.

It looks like `71305` is the Page ID of the target page.

**Comment by nreckart** [comment]
Internally linked pages should now be linked to correctly in the admin view.
