### ISSUE TITLE
JavaScript, ES6, Uglifier gem, Terser and transpilation

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#261]
## Background

CleanSlate currently uses the [Uglifier gem](https://github.com/lautis/uglifier/) to concatenate and minify JavaScript. Out of the box, this gem does not work with (or transpile) [ES6](https://www.quora.com/What-is-ES6?share=1). If it finds ES6 in a JavaScript source file, it errors out and the whole file will not load.

ES6 is becoming more and more prevalent these days. IE11 is the only browser to not support ES6 at this time. IE11 will also be unsupported by most organizations (likely including WVU) by the end of 2021. CleanSlate designers and developers are finding JavaScript plugins that use ES6 (things like arrow functions `=>`, `let`, `const`, etc). They're able to use these locally via Hammer, but when they push to production, the JS file pukes because it has ES6 in it (404, "Holy moly, we just blew a fuse...").

### Option 1

We could enable experimental "Harmony Mode" for the Uglifier Gem. There are some notable and not insignificant questions here:

  * > Disabling mangling and compressing is recommended with Harmony mode.
    * By default, our themes ship to compress and mangle JS via `config.yml`
  * Issue: [Is harmony mode still considered experimental?](https://github.com/lautis/uglifier/issues/142)

### Option 2

Switch to the [ruby-terser](https://github.com/ahorek/terser-ruby/) gem. Terser supports ES6 out of the box.

While [Terser](https://terser.org/) is widely used in the JS community, it's not nearly as popular in the Ruby/Rails world. We would have to do some testing to make sure this change doesn't break all JS files in CleanSlate.

### Option 3

Leave everything as is. Make CleanSlate designers and developers use [Babel](http://babeljs.io/) in their [Gulp](https://gulpjs.com/) workflows to transpile ES6+ to ES5. 

One potential negative of this approach is that some CleanSlate developers don't know JavaScript and thus don't understand what Babel is or why they'd need it, not to mention how to configure Babel.

## What to do

I'd wager it would be worth trying Terser locally and maybe seeing what it does on staging. Since IE11 is on its last legs, we will soon be able to use ES6 in production and not have to do any transpilation. Having the ability to push ES6 to CleanSlate and have it run in production is a valid medium term goal. 

Alternatively, we could do nothing and place the onus on transpilation on theme designers and developers until we officially drop support for IE11.

## TODO

  * ~~Document Uglifier / ES6 "Holy moly we just blew a fuse" on the [CleanSlate CMS site](https://cleanslatecms.wvu.edu/how-to/theme-development/) to tell people to transpile their JS~~ [DONE](https://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-include-javascript).

**Comment by adamjohnson** [comment]
In case anyone comes across this issue looking for Gulp + Babel + CleanSlate + ES6 transpilation, I created a project using these tools for the Refresh website in August 2020: [ur-student-activity-series](https://bitbucket.org/wvudigital/ur-student-activity-series/src/master/) on Bitbucket.

**Comment by adamjohnson** [comment]
Update: we're playing with Terser (via the Terser gem) in Staging to see if it'll work for our needs. See relevant commit: https://github.com/wvuweb/cleanslate/commit/f215d51d096fe5f366d3798e3f01ae37d2211088.

The JavaScript that ships with Bootstrap v5 is all ES6, so trying to get ahead of this when we move in that direction.

I should note that if you set `compress` and `mangle` to `false` in [`config.yml`](https://github.com/wvuweb/wvu-design-system/blob/master/config.yml#L106-L107), you can use ES6 in production CleanSlate themes today—you just lose those benefits / have to take care of them yourself via Gulp, et all.

**Comment by adamjohnson** [comment]
Another update (via [Slack](https://wvu-ur-web.slack.com/archives/C02UQS8QR/p1621961160000400)):

As promised, I did a test of Terser with ES6 on Staging (http://refresh.volutus.wvu.edu/). From my limited test, it seems to be working--meaning, CleanSlate is serving ES6 (arrow functions `=>`, template literals, rest operators, `let`, `const`). You can see it in this file:

http://refresh.volutus.wvu.edu/javascripts/1621960241/vendor/dayjs/dayjs.min.js&vendor/dayjs/localizedFormat.js&dayjs-hook-up-plugins.js&babel/src/pull-acuity-events-for-isotope.js

If this file were using Uglify, it would result in an application error / "Holy moly, we just blew a fuse."

I don't know exactly what we're looking for to move Terser from Staging to Prod, but maybe this data point can help in some way.

**Comment by nreckart** [comment]
Sounds good to me. WIthout any objections, I'll deploy Terser to production later today.

**Comment by adamjohnson** [comment]
Terser has now been deployed to production. So far, so good.

I updated [the docs](https://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-include-javascript#es6-notes) to note we now support ES6+. There is a pull request (wvuweb/cleanslate#96) under review to add `module`/`nomodule` support.

After a few days, if we don't see any errors/anything funky, we can close this issue.

**Comment by adamjohnson** [comment]
Everything seems fine here. I'm going to close this issue. Really stoked on this one! 🎉
