### ISSUE TITLE
Ability to search for assets via Asset ID

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/cleanslate-cms#262]
Feature request:

Ability to use the asset id to search for assets in Cleanslates file manager.

I can access an asset id by viewing the page source via the `data-asset-id`.  It would be nice to be able to use that in the search results for assets.  Most often or not the file is not named the same as how it is linked.  Digging through all assets is time consuming more then it needs to be.

Example:
```html
<img alt="Alliance for Excellent Education" data-asset-id="136561" data-asset-version="380x162" src="/files/372670f4-9a77-43af-a4cd-7a526162ce64/380x162?cb=1568922955">
```

Another place would be nice to show this asset id is when you click on a linked media image in the editor and it opens a modal, if you are coming at it from the admin point of view.

I'm assigning myself this task.  Will take a stab at implementation.

**Comment by adamjohnson** [comment]
![Screenshot of Files showing how to hover over an image preview to get the asset ID](https://user-images.githubusercontent.com/575865/117190342-4bf18900-adad-11eb-8e06-9fccb8396b3b.png)

For reference, you can get the asset ID by hovering over the small preview thumbnail. But yes, incorporating this into search results would be helpful. 👍

**Comment by nreckart** [comment]
The ability to search for an asset by ID has been implemented.
