### ISSUE TITLE
Show and hide slots

### ISSUE THREAD

**Issue by bokster** [wvuweb/cleanslate-cms#265]
Currently, when a client wants to hide information (to use again later) in a slot, you do it by going to the said slot and leave the option blank in the dropdown. But this is not an obvious action.

A way to signify show/hide (checkbox?) would be welcomed.

<img width="785" alt="Screen Shot 2021-09-30 at 2 59 32 PM" src="https://user-images.githubusercontent.com/289061/135515634-5225863f-1f15-4650-a83b-bcfeae6d00a2.png">

**Comment by adamjohnson** [comment]
This issue is probably better suited for the [Design System repo](https://github.com/wvuweb/wvu-design-system/issues) since it relates directly to a specific theme / theme functionality. Kindly open this issue there.
