### ISSUE TITLE
404 Not Found template for attachments

### ISSUE THREAD

**Issue by bokster** [wvuweb/cleanslate-cms#266]
Currently, when a user clicked on a PDF that's no longer on a website, the resulting page looks like this [https://adventurerecreation.wvu.edu/files/d/f0%20add/qrg1-view-a-green-sheet.pdf](url)

Is there a way to make it look like the 404 Not Found page?

**Comment by nreckart** [comment]
Missing file requests should now be redirected to the site's custom 404 page, if one exists.
