### ISSUE TITLE
Sitemap Update: Remove /[default-path] and Replace with /

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#270]
Statwax wants us to modify our sitemap feature. Currently, this is how the default page for online.wvu.edu is represented in the sitemap:

```
<url>
<loc>https://online.wvu.edu/home</loc>
<lastmod>2022-01-12T08:52:58-05:00</lastmod>
</url>
```

They would like it to be:

```
<url>
<loc>https://online.wvu.edu/</loc>
<lastmod>2022-01-12T08:52:58-05:00</lastmod>
</url>
```

I think looking at the default page for a site and just making it the base URL in the settings is a good enough change.

**Comment by adamjohnson** [comment]
Related to #263.

**Comment by nreckart** [comment]
@dmolsen Does it hurt to have items for both URLs in there? So  https://online.wvu.edu/ and https://online.wvu.edu/home.  Or should it ONLY be the root?

**Comment by dmolsen** [comment]
Only the root.
