### ISSUE TITLE
Add Support for *.wvu.edu Google Tag Manager Container

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#274]
## Background

CleanSlate CMS currently supports a *.wvu.edu Google Analytics (GA) account. This tracks all traffic to public pages in CleanSlate. We have added the GA account to www.wvu.edu to make analytics more comprehensive.

I would like to replace the GA code with a similar *.wvu.edu Google Tag Manager (GTM) account that contains the *.wvu.edu GA account, a *.wvu.edu GA4 account and upgraded event tracking for things like outbound links. This will allow us to add deeper goal tracking for our sites.

## Implementation

This would affect the `html_injector` code. It is two separate pieces of code compared to the single GA snippet/template. The following global code should be removed from the existing `GOOGLE_ANALYTICS_TEMPLATE`:

```
ga('create', 'UA-31189476-28', 'auto', {'name': 'wvuglobal'})
ga('wvuglobal.send', 'pageview');
```

I believe the following would become two "templates" in the `html_injector` code.

Per Google, "Paste this code as high in the <head> of the page as possible:"

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WPD5W8R');</script>
<!-- End Google Tag Manager -->
```

Per Google "Additionally, paste this code immediately after the opening <body> tag:"

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe aria-hidden="true" src="https://www.googletagmanager.com/ns.html?id=GTM-WPD5W8R"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

## Summary of Deliverables

We should be able to go into the *.wvu.edu GA account and continue to see real-time activity. We'd also see an increase in events (e.g. outbound link clicks).

**Comment by nreckart** [comment]
This has been deployed to production.

I put the GTM code in the ENV config for CS. Seemed appropriate and allows it to be changed without needing to deploy the app. Also makes it easier to test.

I assume things are working as they should. Nothing has blown up on the CS side, that I'm aware of. 

@dmolsen let me know what you see in the AM. Reopen this issue if needed.

**Comment by dmolsen** [comment]
@nreckart -

This is working. I had a bug with my tags but, two hours later, it's all fixed and running.
