### ISSUE TITLE
Adding LookerStudio Report Link to CleanSlate Site Overview

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/cleanslate-cms#278]
Tatsu and I would like a Google Analytics 4 "pane" in the Site Overview similar to the "Siteimprove" and "Site information" panel. We would like it to go between those two panes. I believe that the file to edit would be `cleanslate/app/views/sites/show.html.erb` 

The example code would be:

```
<section aria-labelledby="aria__siteimprove-score" class="cs-siteimprove-score__section cs-box span7">
  <div class="cs-box__header">
    <strong id="aria__siteimprove-score">Google Analytics 4</strong>
  </div> <!-- /.cs-box__header -->
  <p class="span10">
    📈 Use our <strong>draft</strong> <a href="https://lookerstudio.google.com/u/0/reporting/1741705d-e05a-4ab2-abac-74d65a6c703e/page/AKZHD?params=%7B%22ds140.filterhostname%22:%22[[PRIMARY_DOMAIN]]%22%7D">GA4 analytics dashboard</a> to view this websites's web traffic.
  </p>
  <p class="cs-siteimprove-score__support-copy cs-siteimprove-score__support-copy--bordered span10">
    Have feedback about this dashboard? Contact Tatsu Johnson with your suggestions.
  </p>
</section> <!-- /.cs-box -->
```

IMPORTANT ITEM: The `[[PRIMARY_DOMAIN]]` should be replaced by the primary domain for the site. For example, `admissions.wvu.edu`. This way people will see the analytics for their primary domain.

**Comment by nreckart** [comment]
Added the GA4 stuff to the site overview page as Dave suggested.
