### ISSUE TITLE
Use Cookie-Free Domains

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#35]
_From @dustinmazon on March 5, 2014 17:24_

I ran a test using the YSlow extension for Chrome on the diyoutdoors.wvu.edu site.

![screen shot 2014-03-05 at 12 10 29 pm](https://f.cloud.github.com/assets/1126703/2335914/1c5a5e22-a489-11e3-96f7-9900dc665501.png)

Here's what the suggestion says for YSlow:

When the browser requests a static image and sends cookies with the request, the server ignores the cookies. These cookies are unnecessary network traffic. To workaround this problem, make sure that static components are requested with cookie-free requests by creating a subdomain and hosting them there.

http://developer.yahoo.com/performance/rules.html#cookie_free

I was thinking all Cleanslate static assets (only files / assets located in a theme) could be hosted on a subdomain with the settings to enable cookie-free requests. 

_Copied from original issue: wvuweb/cleanslate#34_

**Comment by dmolsen** [comment]
I'm going to close this issue. It's a nice-to-have but it's not killing our performance or anything.
