### ISSUE TITLE
Show more than 3 blog articles exist after expanding the "Blog Index" page in the sitemap.

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#36]
_From @adamjohnson on March 5, 2014 17:26_

## Steps to reproduce the issue:

Create a blog with more than 3 articles. Expand the Blog parent page. It will look like this:

![Direct Link](https://s3.amazonaws.com/f.cl.ly/items/261E0f3I2V2p1X1G3i15/blog-posts.png)

## Results

The sitemap will only show the 3 latest articles. 

## Expected Behavior

Seeing only 3 articles after expanding the blog parent page is misleading. There should be a visual cue explaining more than 3 articles exist. Perhaps like so:

![Direct Link](https://s3.amazonaws.com/f.cl.ly/items/463P262J400A2s3Y0P3j/blog-posts-visual-cue.png) 

"Showing 3 of 26 posts".

This could also say "Showing 3 of 20+ posts" or something to that effect. 

Ideally, this text would fade in when you click to expand the Blog Index page.

Another option might be something saying ["View all blog posts..."](http://cl.ly/UFn6). Although I like "Showing 3 of 26 posts" better. 

I'm sure there are other ways to do this. If you have other suggestions, please leave a comment.

_Copied from original issue: wvuweb/cleanslate#35_

**Comment by adamjohnson** [comment]
_From @zeroedin on October 31, 2014 17:17_

What about adding an additional div row under the "last" page of the blog stack that is a darker blue with a link that says "More Articles... " then repeating the "Showing 3 of 26" message.  I feel like putting the message top and the bottom is a better visual clue as by the time people get to that point they are probably past the point of looking at the "Blog" row.

**Comment by adamjohnson** [comment]
I'm game for either one.

**Comment by adamjohnson** [comment]
+1 from Tatsu on this:

  > ​This may sound like a weird question, but if you have a blog on CleanSlate, is there a limit to how many articles shows up on the "pages" interface? I am trying to get to a blog article that is the fourth oldest one, but it doesn't show up in the pages section. I can search it without any problems, but I was just wondering if it could be changed to display more. Thanks,

  > -Tatsu Johnson

**Comment by adamjohnson** [comment]
Another idea from Tatsu:

  > It does, but mine only shows the last three articles. But I input them all in there within a few days. So, if I had a fourth article that I had done only a few days ago, I would have to manually search it to find it. 
My ideas was instead just three, put a time limit on how long they will stay up, like  a month. That would give some more time for catching mistakes and editing things such as tags.

**Comment by adamjohnson** [comment]
_From @nreckart on January 16, 2015 18:24_

You do know that there is a link on the blog index page to view all articles, right? That doesn't solve the "Only 3 are visible with no obvious visual cue that there are more articles" problem, but you don't have to "manually" search for the other articles.

**Comment by adamjohnson** [comment]
Yup. Crystal.

**Comment by dmolsen** [comment]
I would like to see @zeroedin's idea implemented. It's a good solution.

**Comment by adamjohnson** [comment]
I think, between these last two commits, this will be fine for now.

Current status: Shows up to 50 blog posts and the link text has changed to "View All Articles".

**Comment by nreckart** [comment]
Implementing Steve's suggestion would be ideal, but doing so would require quite a bit of hacking due to how the page tree it built. You'd basically have to fake a page node in order to get the div inserted. Not saying it's impossible, just punting it for now.
