### ISSUE TITLE
Add Expires Headers

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#37]
_From @dustinmazon on March 5, 2014 17:42_

Visiting diyoutdoors.wvu.edu I ran the YSlow extension for Chrome and was wondering what we could do to set expiration dates for our static content.

![screen shot 2014-03-05 at 12 28 11 pm](https://f.cloud.github.com/assets/1126703/2336142/be55324a-a48b-11e3-8297-7f341a424064.png)

http://developer.yahoo.com/performance/rules.html#expires

<hr>

Would there be a way for front-end developers to manage a themes/templates expire headers for static assets? Maybe use the YML file?

<hr>

Adam mentioned that we could set a far-future expiration date on all assets and then make sure every file name gets a unique id string added to the end of the user generated file name. 

Example:   wvu-logo-id93hn576xdfmkewyt231.jpg

The original file name was wvu-logo.jpg and then when it was committed the unique string was added to the end of the file name. Every time an asset is committed the unique string is changed. 

Another possible alternative is to make developers use unique file names by versioning everything. 

Example: 
wvu-logo-1.jpg
wvu-logo2.jpg

_Copied from original issue: wvuweb/cleanslate#36_

**Comment by dmolsen** [comment]
Expires headers can be handled two ways:

* we set a long time out and prof techs ensure that they rename files each time they update them. perhaps by adding a version string. this will also mean updating theme files.
* we set a long time out and clean slate adds the version/timestamp string itself.

I highly doubt option 1 is ever going to happen on a consistent basis. On option 2 I'm not sure Clean Slate supports that from a theming perspective. Essentially what would happen is:

1. prof tech updates styles.css
2. in the theme we have a dynamic tag to include styles.css
3. when writing out the link to styles.css clean slate renames it to styles.[update-timestamp].css
4. when the browser requests styles.[update-timestamp].css clean slate is smart enough to return styles.css

If option 2 is not easily possible @nreckart then I will close out this issue.

**Comment by adamjohnson** [comment]
It's worth mentioning `styles.123456.css` is preferable to `styles.css?v=123456` as the following blog post mentions:

http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

(I didn't know this)

**Comment by nreckart** [comment]
I'm in the process of implementing @dmolsen's second option where the system automatically adds a version to the URLs for theme JS, CSS, and images. The version will be incremented whenever a theme is synced within CleanSlate.

Examples:
/stylesheets/1422656495/site.css
/javascripts/1422656495/site.css
/images/1422656495/wvu-logo.jpg

**Comment by nreckart** [comment]
Adding a version to the stylesheets URLs as described above breaks image URLs embedded within the CSS.

For example:
`background: url(../images/background.png) no-repeat left -254px; }`

The above will generate `/stylesheets/images/background.png` when the version is added to the stylesheet URL, which results in a 404. 

Using an absolute path, such as `/images/background.png`, would generate a valid URL, but without the version info, which means the only way to bust the cache would be for designers to manually update the URL within the CSS anytime they modify the image. That is obviously not ideal, but without the system automagically processing image URLs within the CSS at render time, there's really no way around it. I'll look into the possibility of the system handling it, but it may be a rabbit hole.

**Comment by nreckart** [comment]
I deployed some changes that allow the system to process URL references to theme images within theme CSS, replacing them with a properly versioned URL. Basically, background images and such referencing '../images/some-image.png' will be rewritten to '/images/123455/some-image.png', where 123456 is based on when the theme was last synced.

Example:
`background: url(../images/background.png) no-repeat left -254px; }`

becomes

`background: url("/images/123456/background.png") no-repeat left -254px; }`

So syncing a theme should now bust caches for all of the following:
- Stylesheets
- JavaScripts
- Images
- Images used in theme CSS

**Comment by dmolsen** [comment]
@adamjohnson -

Can you please write a blog post on this before COB Thursday after double-checking that this is working? This is a nice big change for folks. I think you'd be better explaining it to designers than I. Highlight:
- cache clear on theme update so no more lag there
- we're trying to be smarter about caching static assets which should speed up people's page load times. 

fwiw, i checked the cache on webpagetest.com and it's looking good. clean slate cms gets a B in the category. nice job, @nreckart.

**Comment by nreckart** [comment]
I would expect to see a negative impact on system performance and a minimal increase in browser performance.

**Comment by adamjohnson** [comment]
Dave, this seems like an excellent post for you to do, seeing as this is [kind of](http://www.dmolsen.com/2012/11/08/talking-mobile-web-performance-ress-in-smashing-magazines-the-mobile-book/) [your thing](http://www.dmolsen.com/2013/04/18/responsive-web-design-measuring-web-performance/).

I'm happy to confirm that there's no more lag after someone hits Sync Theme as much as I can. I can be an editor for your post and make sure the copy is readily understandable for our designers.

I'd like to get more people contributing to the [CleanSlate blog](http://cleanslatecms.wvu.edu/blog), so this seems like a great opportunity.

**Comment by dmolsen** [comment]
Bah, fair enough. Will do :)

**Comment by dmolsen** [comment]
We're now consistently getting grades of B in this area on WebPageTest. That's good enough for me. I still need to write up the blog post but in the interest of clearing issues that have actually been fixed I'm closing this.
