### ISSUE TITLE
Enable/Allow CORS

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#79]
_From @adamjohnson on November 21, 2014 20:37_

We serve a lot of things from [code.wvu.edu](http://code.wvu.edu). I just realized CleanSlate's CORS (Cross-Origin Resource Sharing) policy doesn't allow us to link to resources _at the second level_ from within the Code repo. It'll let you load a stylesheet, but if that stylesheet calls an image, font, etc, said image, font, etc gets disallowed:

http://agriculture.sandbox.wvu.edu/

![https://s3.amazonaws.com/f.cl.ly/items/1U3n1I2v2l3J1V0k4040/busted-icon.png](https://s3.amazonaws.com/f.cl.ly/items/1U3n1I2v2l3J1V0k4040/busted-icon.png)

Notice the missing left, right, and pause icons for Flexslider. They're shown as squares instead of [their proper icons](http://flexslider.woothemes.com/). Here's the console error:

  > Font from origin 'http://code.wvu.edu' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://agriculture.sandbox.wvu.edu' is therefore not allowed access.

Here's the H5BP apache config stuff for CORS: https://github.com/h5bp/server-configs-apache/tree/master/src/cross-origin

And a quick google search reveals there's a [Rack CORS gem](https://github.com/cyu/rack-cors) as well as a blanket [allow anything with CORS policy](http://stackoverflow.com/a/18225624/4032506) for rails.

One of the biggest things this affects is Flexslider since [we recommend](http://cleanslatecms.wvu.edu/how-to/theme-development/setting-up-flexslider-snippet) serving Flexslider's assets (CSS & JS) from the Code repo. I've deployed a couple of sites that support the Flexslider snippet, so it would be helpful to get this resolved in a timely manner.

_Copied from original issue: wvuweb/cleanslate#78_

**Comment by adamjohnson** [comment]
_From @zeroedin on November 21, 2014 21:1_

I would **not** open CORS up blindly or blanket it.  CORS can be a [security risk](https://code.google.com/p/html5security/wiki/CrossOriginRequestSecurity).

Rather white listing specific domains and for specifics needed resources only, in this case `code.wvu.edu`.

http://support.maxcdn.com/how-to-use-cdn-with-webfonts/

```apache
# Webfont access
# ----------------------------------------------------------------------
# Allow access from all domains for webfonts.
# Alternatively you could only whitelist your
# subdomains like "subdomain.example.com".
<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|font.css|css)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>
```

**Comment by adamjohnson** [comment]
Trouble is there will be multiple sites and repos that become shared (WVU Tech already has one, I'm sure Eberly and others are in the pipe). 

The best thing to do would be to decide what we want to allow via CORS. I think the H5BP server configs will probably be a great starting point here.

Definitely open to ideas in this space.

**Comment by adamjohnson** [comment]
_From @nreckart on December 1, 2014 15:36_

So how did this work on old slate?

**Comment by adamjohnson** [comment]
We never had any issues referencing things across repos in Slate 1. I don't know the details though.

**Comment by adamjohnson** [comment]
_From @zeroedin on December 1, 2014 15:39_

From 1-common.conf for slate.
```apache
<IfModule mod_headers.c>
    <FilesMatch "\.(eot|font.css|otf|ttc|ttf|woff)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>
```

**Comment by adamjohnson** [comment]
_From @nreckart on December 1, 2014 15:43_

Ok so then I propose the following for the CleanSlate apache confg to allow for images, fonts, and timing. Any objections? @jja006 you good with this?


```
# ----------------------------------------------------------------------
# | Cross-origin images                                                |
# ----------------------------------------------------------------------

# Send the CORS header for images when browsers request it.
#
# https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
# https://blog.chromium.org/2011/07/using-cross-domain-images-in-webgl-and.html

<IfModule mod_setenvif.c>
    <IfModule mod_headers.c>
        <FilesMatch "\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp)$">
            SetEnvIf Origin ":" IS_CORS
            Header set Access-Control-Allow-Origin "*" env=IS_CORS
        </FilesMatch>
    </IfModule>
</IfModule>

# ----------------------------------------------------------------------
# | Cross-origin resource timing                                       |
# ----------------------------------------------------------------------

# Allow cross-origin access to the timing information for all resources.
#
# If a resource isn't served with a `Timing-Allow-Origin` header that
# would allow its timing information to be shared with the document,
# some of the attributes of the `PerformanceResourceTiming` object will
# be set to zero.
#
# http://www.w3.org/TR/resource-timing/
# http://www.stevesouders.com/blog/2014/08/21/resource-timing-practical-tips/

<IfModule mod_headers.c>
    Header set Timing-Allow-Origin: "*"
</IfModule>

# ----------------------------------------------------------------------
# | Cross-origin web fonts                                             |
# ----------------------------------------------------------------------

# Allow cross-origin access to web fonts.

<IfModule mod_headers.c>
    <FilesMatch "\.(eot|otf|tt[cf]|woff2?)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>```

**Comment by adamjohnson** [comment]
What about https://github.com/h5bp/server-configs-apache/blob/master/src/cross-origin/requests.conf (seeing as we're gonna use everything else there)?

**Comment by adamjohnson** [comment]
_From @nreckart on December 1, 2014 15:51_

No

**Comment by adamjohnson** [comment]
_From @zeroedin on December 1, 2014 15:53_

http://stackoverflow.com/questions/14979313/possible-security-issues-of-setting-access-control-allow-origin

**Comment by adamjohnson** [comment]
_From @zeroedin on December 1, 2014 15:55_

Slide 23 +

http://www.slideshare.net/null0x00/cors-and-insecurity

**Comment by adamjohnson** [comment]
_From @nreckart on December 1, 2014 16:1_

Slide 30 in the above deck also does a good job explaining the security risks.

**Comment by dmolsen** [comment]
@jja006 -

We just need a good idea on if this is actually possible or not. If it's not let's close this out.

**Comment by dmolsen** [comment]
In discussion between @jja006 & @zeroedin we feel that this is a bit too cumbersome to implement. Others have found ways around this anyway.
