### ISSUE TITLE
Better reorder pages UI

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#85]
_From @adamjohnson on January 6, 2015 17:41_

We've discussed ways to handle page reorganization better than the current Parent > Sort order UI. 

Ideas are:

  1. Drag and Drop
  1. Put page Above/Below/Child of X (X being a Select2 field of pages in a site)

After learning from Slate and examining [options](https://github.com/RamonSmit/Nestable) out there, drag and drop feels fairly cumbersome for bigger sites. It's great if you're just reordering, say, 1-20 items. But, when you get more items than that, it starts to fall over on itself.

So, our current plan is to go with option 2 from above. The UI for this would go in the same location as "Parent > Sort Order" is right now. Sort order (the most confusing thing in page properties) would go away and be handled on the back end.

There was talk of making "Child of" be dynamically shown after a user selects a page.

If anyone has any other input on this, please speak up ASAP or forever hold your peace (@dustinmazon I know you had some input). 

_Copied from original issue: wvuweb/cleanslate#84_

**Comment by dmolsen** [comment]
The new angle that @nreckart is taking on this is pretty slick.

**Comment by nreckart** [comment]
This was deployed on Jan. 28.
