### ISSUE TITLE
Default template for new pages

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/cleanslate-cms#91]
_From @adamjohnson on January 16, 2015 16:58_

Allow themes to have a configurable default template in `config.yml`.

  > Quick question for you - can you set a default page theme in cleanslate? Right now they are in alphabetical order, and I'd like to be able to set a good default as the standard default theme.

If the variable is not set, default to alphabetical order.

Something like this (or thereabouts):

```yaml
theme:
  template:
    default: backpage.html
```

_Copied from original issue: wvuweb/cleanslate#91_

**Comment by adamjohnson** [comment]
_From @nreckart on January 20, 2015 18:5_

Implemented in 2b1d3a3028a2.

**Comment by nreckart** [comment]
A default template can be defined in config.yml for each page type as follows:

```yml
default_templates:
  content: backpage
  article: blog_article
  blog: blog_index
  error: backpage
```

This should probably go in the cleanslate-toolkit, @adamjohnson.

You could also use the special *any* definition to set a default for any page types that aren't specifically defined.

```yml
default_templates:
  any: backpage
  blog: blog_index
```

In the example above, any *Blog* pages would default to the *blog_index* template, while all others would default to the *backpage* template.

**Comment by adamjohnson** [comment]
This default template configuration has been added to the CleanSlate Toolkit. See:

https://github.com/wvuweb/cleanslate-toolkit/commit/b363bbe8de85d1b61f6ce73135efdbcaa8d5be42
