### ISSUE TITLE
Add the ability to maintain site labels

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#98]
Provide a UI for maintaining labels used to organize pages and files for individual sites.

**Comment by adamjohnson** [comment]
This feature has been implemented in wvuweb/cleanslate@a7aa833dc56d33cf93a70678b3a91a0e5f344e89. @nreckart changed permissions to enable Site Admins and up to manage labels in wvuweb/cleanslate@d6ce204bc62a1fb8cd6140eb893813cbc895b98d.

Go to Manage > Labels to use the new feature.
