### ISSUE TITLE
Password protected pages

### ISSUE THREAD

**Issue by nreckart** [wvuweb/cleanslate-cms#99]
Add the ability to password protect pages.

**Comment by nreckart** [comment]
This functionality has been implemented and is in hold until the Rails 4 branch is deployed. 

It will also necessitate forcing SSL across all responses, both public and private. @jja006 @dmolsen we need to work out the details on that SSL bit.

**Comment by dmolsen** [comment]
One big issue here is the SSL cert. The to-do list:

 - [ ] see if we can get all hostnames using wildcards *.research added to the existing overall cert via the Subject Alternative Name. we can't just add *.research. we have to add vp.research, foo.research, bar.research separately
 - [ ] gather a list of all hostnames on those wildcards if possible

After we make the switch we can no longer have sub-subdomains. AFAIK, that would require re-issuing the cert and I don't think we want to put that work on anyone.

**Comment by adamjohnson** [comment]
I imagine there will be a lot of something.whatever.wvu.edu sub-subdomains.

Some that come to mind are:

  * 2009.happyholidays.wvu.edu (all the way through 2013 and beyond as the years roll through)
  * whatever.studentorgs.wvu.edu - These are likely to be created daily when SOS moves to CleanSlate.

I'm sure Jay can provide more details on the amount of sub-subdomains that we have.

___________________________

Another part of this will be to communicate with the college prof techs to make sure their themes are SSL ready (I'd gamble that 60%+ are not at this point). This can be as simple as being sure to use `//whatever.com/styles.css` instead of `http://whatever.com/styles.css`. I doubt many understand the difference.

**Comment by dmolsen** [comment]
We're going to have to kill *.studentorgs.wvu.edu. At some point we would have made the switch, they'll want a new site and we won't be able to update the cert. If it becomes a dash or whatever (e.g. foo-studentorgs.wvu.edu) we need to come up with a future friendly solution on these wildcards. Maybe re-issuing the cert is ridiculously easy but I sort of doubt it. At the very least, it's yet another step when setting up sites and it sort of kills the magical-ness of having the wildcard in the first place.

**Comment by dmolsen** [comment]
@jja006 -

The primary issue at the moment is that we need to follow-up with ITS on our options for adding SSL support to everything in clean slate. Please add that to your notes for your next meeting. Options seem to be:

* some magical *.*.wvu.edu SSL cert. we should see if we can find some way to push the funding of it if it exists.
* track down costs on *.[subdomain].wvu.edu SSL certs and if it's feasible for ITS to put those on the F5
* figure out a migration strategy to move from four part subdomains to something else and then add redirects. i originally thought we might be able to go with secondary names but i think that will be setting us up for failure. just need to bite the bullet that we need a real migration plan.

**Comment by dmolsen** [comment]
ITS rep was positive to the suggestion and is looking into logistics and cost for the `*.[subdomain].wvu.edu` SSL certs.

**Comment by jja006** [comment]
We addressed the issue with managing the SSL cert for this by using AWS ACM and a specific Cloudfront distro for sites with the requirement for password protected pages.

We're using a wild-card cert in ACM with multiple wild-card names assigned, and the specific distro was also needed to handle caching and headers as needed for the password protected behavior.

ITS also implemented some new options for internal file and document sharing, and other "intranet" like use-cases; we recommend using those for the cases where that's a better fit.

Nathan, do you want to add any comments and close this as completed? Thanks.

**Comment by nreckart** [comment]
There is an option in site settings that must be enabled for this to work for a site, in addition to the site's domain being added to the specific CloudFront distro setup for this purpose.
